---
title: "EEMs exploration"
author: "Dexter Howard"
date: "2023-06-23"
output: html_document
---

## Read in packages 

```{r, include = F}
library(tidyverse)
library(scales) #for date format on plots
library(patchwork) #arrange figures w/ slashes and lines
library(plotly)
library(viridis)

```

## Get data 

```{r}
## EEMs plunge point data subset 
# eems_cove <- read.csv("./EEMs_Results_CCR_plungepoint_subset.csv")
eems_cove <- read.csv("./EEMs_chem_2023_plungepoint.csv") |> 
  rename(DOC_mgL = TOC_mgL) |> 
  mutate(HIX = ifelse(HIX < 0, NA, HIX),
         HIX = ifelse(HIX > 16, NA, HIX),
         BIX = ifelse(HIX < 0, NA, BIX),
         BIX = ifelse(HIX > 16, NA, BIX))
  #filter(HIX > 0, HIX < 16) #remove crazy -200 and suspect 17 both in SMB

##info on dataframe 
#EEMS and lachat and DOC data in csv
#sites are coded as: streams == X000, pool == X00, pelagic == 50, cove == X0, coveB == X
##Distances from SMB 
# Distance = ifelse(Site_num == 3000, 0, NA),
# Distance = ifelse(Site_num == 300, 65, Distance),
# Distance = ifelse(Site_num == 30, 430, Distance),
# Distance = ifelse(Site_num == 3, 600, Distance), #fake distance for plotting
# Distance = ifelse(Site_num == 50, 900, Distance) #fake distance for plotting
         
##Distances for HPB
# Distance = ifelse(Site_num == 1000, 0, NA),
# Distance = ifelse(Site_num == 100, 125, Distance), #fake distance for plotting
# Distance = ifelse(Site_num == 10, 249, Distance),
# Distance = ifelse(Site_num == 50, 900, Distance) #fake distance for plotting


```


## Site 50 plotting

```{r}
## HIX
eems_cove |> 
  mutate(Date = mdy(Date)) |> 
  filter(Date < ymd("2023-08-08")) |> 
  select(1:6, HIX) |> 
  filter(Site == 50) |> 
  ggplot(aes(x = Date, y = HIX, color = Depth_m))+
  geom_point(size = 2.5)+
  # facet_wrap(~Date, ncol = 3)+
  ggtitle("Site 50 HIX")+
  theme_bw()+ theme(legend.position = "top")+
    scale_color_manual(values = c("0.1" = "#000000", "1.5" = "#E69F00", "6" = "#56B4E9", "9" = "#009E73", "20" = "#F0E442"))

eems_cove |> 
  mutate(Date = mdy(Date)) |> 
  filter(Date < ymd("2023-08-08")) |> 
  select(1:6, HIX) |> 
  filter(Site == 50) |> 
  ggplot(aes(x = HIX, y = as.numeric(Depth_m)))+
  scale_y_reverse()+
  geom_line(orientation = "y")+
  geom_point(size = 2.5)+
  facet_wrap(~Date, ncol = 3)+
  ggtitle("Site 50 HIX")+
  theme_bw()


## DOC
eems_cove |> 
  mutate(Date = mdy(Date)) |> 
  filter(Date < ymd("2023-08-08")) |> 
  select(1:6, DOC_mgL) |> 
  filter(Site == 50) |> 
  ggplot(aes(x = Date, y = DOC_mgL, color = Depth_m))+
  geom_point(size = 2.5)+
  # facet_wrap(~Date, ncol = 3)+
  ggtitle("Site 50 DOC")+
  theme_bw()+ theme(legend.position = "top")+
    scale_color_manual(values = c("0.1" = "#000000", "1.5" = "#E69F00", "6" = "#56B4E9", "9" = "#009E73", "20" = "#F0E442"))

eems_cove |> 
  mutate(Date = mdy(Date)) |> 
  filter(Date < ymd("2023-08-08")) |> 
  select(1:6, DOC_mgL) |> 
  filter(Site == 50) |> 
  ggplot(aes(x = DOC_mgL, y = as.numeric(Depth_m)))+
  scale_y_reverse()+
  geom_line(orientation = "y")+
  geom_point(size = 2.5)+
  facet_wrap(~Date, ncol = 3)+
  ggtitle("Site 50 DOC")+
  theme_bw()

```


## SMB

```{r}
levels_distances <- c("Stream", "Pool", "Cove A", "Cove B", "Site 50")

## HIX
# eems_cove |> 
#   mutate(Date = mdy(Date)) |> 
#   filter(Date < ymd("2023-08-08")) |> 
#   select(1:6, HIX, TOC_mgL) |> 
#   filter(Site_num %in% c(50,3,30,300,3000)) |> 
#   mutate(Distance = ifelse(Site_num == 3000, "Stream", NA),
#          Distance = ifelse(Site_num == 300, "Pool", Distance),
#          Distance = ifelse(Site_num == 30, "Cove A", Distance),
#          Distance = ifelse(Site_num == 3, "Cove B", Distance), 
#          Distance = ifelse(Site_num == 50, "Site 50", Distance) 
#          ) |> 
#   mutate(Depth_m = ifelse(Depth_m == "SURF", 0.1, Depth_m),
#          Depth_m = ifelse(Depth_m %in% c("BOT", "PD"), 1.5, Depth_m)) |> 
#   ggplot(aes(x = factor(Distance, level = levels_distances), y = TOC_mgL, color = Depth_m))+
#   geom_point()+
#   #ylim(1,15)+ #one crazy outlier at -240, and one really high at 17
#   facet_wrap(~Date, ncol = 1)+
#   ggtitle("SMB HIX")+
#   theme_bw()+
#     scale_color_manual(values = c("0.1" = "#000000", "1.5" = "#E69F00", "6" = "#56B4E9", "9" = "#009E73", "20" = "#F0E442"))


## grid variables
eems_cove |> 
  mutate(Date = mdy(Date)) |> 
  filter(Date < ymd("2023-08-08")) |> 
  select(1:6, HIX, BIX, FI, DOC_mgL, PO4_ugL) |> 
  pivot_longer(-c(1:6)) |> 
  filter(Site_num %in% c(50,3,30,300,3000)) |> 
  mutate(Distance = ifelse(Site_num == 3000, "Stream", NA),
         Distance = ifelse(Site_num == 300, "Pool", Distance),
         Distance = ifelse(Site_num == 30, "Cove A", Distance),
         Distance = ifelse(Site_num == 3, "Cove B", Distance), 
         Distance = ifelse(Site_num == 50, "Site 50", Distance) 
         ) |> 
  mutate(Depth_m = ifelse(Depth_m == "SURF", 0.1, Depth_m),
         Depth_m = ifelse(Depth_m %in% c("BOT", "PD"), 1.5, Depth_m)) |> 
  ggplot(aes(x = factor(Distance, level = levels_distances), y = value, color = Depth_m))+
  geom_point()+
  #ylim(1,15)+ #one crazy outlier at -240, and one really high at 17
  facet_grid(name~Date, scales = "free_y")+
  ggtitle("SMB")+
  theme_bw()+
    scale_color_manual(values = c("0.1" = "#000000", "1.5" = "#E69F00", "6" = "#56B4E9", "9" = "#009E73", "20" = "#F0E442"))

```


## HPB

```{r}
levels_distances <- c("Stream", "Pool", "Cove", "Site 50")

levels_depth <- c(0.1, 1.5, 6, 9, 20)

## HIX 
# eems_cove |> 
#   mutate(Date = mdy(Date)) |> 
#   filter(Date > ymd("2023-05-04"),
#          Date < ymd("2023-08-08")) |> 
#   select(1:6, HIX) |> 
#   filter(Site_num %in% c(50,1,10,100,1000)) |> 
#   mutate(Distance = ifelse(Site_num == 1000, "Stream", NA),
#         Distance = ifelse(Site_num == 100, "Pool", Distance),
#         Distance = ifelse(Site_num == 10, "Cove A", Distance),
#         Distance = ifelse(Site_num == 50, "Site 50", Distance)
#          ) |> 
#     mutate(Depth_m = ifelse(Depth_m == "SURF", 0.1, Depth_m),
#          Depth_m = ifelse(Depth_m %in% c("BOT", "PD"), 1.5, Depth_m)) |> 
#   ggplot(aes(x = factor(Distance, level = levels_distances), y = HIX, color = Depth_m))+
#   geom_point()+
#   facet_wrap(~Date, ncol = 1)+
#   ylim(1,15)+
#   ggtitle("HPB HIX")+
#   theme_bw()+
#     scale_color_manual(values = c("0.1" = "#000000", "1.5" = "#E69F00", "6" = "#56B4E9", "9" = "#009E73", "20" = "#F0E442"))


## grid variables SITE as factor 
eems_cove |> 
  mutate(Date = mdy(Date)) |> 
  filter(Date > ymd("2023-05-08"),
         Date < ymd("2023-08-08")) |> 
  select(1:6, HIX, BIX, DOC_mgL) |> 
  filter(Site_num %in% c(50,1,10,100,1000)) |> 
    pivot_longer(-c(1:6)) |> 
  mutate(Distance = ifelse(Site_num == 1000, "Stream", NA),
        Distance = ifelse(Site_num == 100, "Pool", Distance),
        Distance = ifelse(Site_num == 10, "Cove", Distance),
        Distance = ifelse(Site_num == 50, "Site 50", Distance)
         ) |>
  mutate(Depth_m = ifelse(Depth_m == "SURF", 0.1, Depth_m),
         Depth_m = ifelse(Depth_m %in% c("BOT", "PD"), 1.5, Depth_m)) |> 
  ggplot(aes(x = factor(Distance, level = levels_distances), y = value, color = factor(Depth_m, levels = levels_depth)))+ # when using categorial sites: factor(Distance, level = levels_distances)
  geom_point()+
  facet_grid(factor(name, levels = c("BIX", "HIX", "DOC_mgL"))~Date, scales = "free_y")+
  #facet_grid(Date~factor(name, levels = c("BIX", "HIX", "DOC_mgL")), scales = "free_y")+
  labs(y = "value", x = "Site", title = "HPB", color = "Depth (m)")+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 14))+
    scale_color_manual(values = c("0.1" = "#000000", "1.5" = "#E69F00", "6" = "#56B4E9", "9" = "#009E73", "20" = "#F0E442"))


## grid variables SITE as DISTANCE
# eems_cove |> 
#   mutate(Date = mdy(Date)) |> 
#   filter(Date > ymd("2023-05-08"),
#          Date < ymd("2023-08-08")) |> 
#   select(1:6, HIX, BIX, DOC_mgL) |> 
#   filter(Site_num %in% c(50,1,10,100,1000)) |> 
#     pivot_longer(-c(1:6)) |> 
#     mutate(Distance = ifelse(Site_num == 1000, 0, NA),
#         Distance = ifelse(Site_num == 100, 150, Distance), #130-170, unsure on exact point
#         Distance = ifelse(Site_num == 10, 300, Distance), #770m to cove B
#         Distance = ifelse(Site_num == 50, 1460, Distance)
#          ) |>
#   mutate(Depth_m = ifelse(Depth_m == "SURF", 0.1, Depth_m),
#          Depth_m = ifelse(Depth_m %in% c("BOT", "PD"), 1.5, Depth_m)) |> 
#   ggplot(aes(x = Distance, y = value, color = factor(Depth_m, levels = levels_depth)))+ 
#   geom_point()+
#   facet_grid(factor(name, levels = c("BIX", "HIX", "DOC_mgL"))~Date, scales = "free_y")+
#   labs(y = "value", x = "Distance from Stream Site (m)", title = "HPB", color = "Depth (m)")+
#   theme_bw()+ theme(legend.position = "top", text = element_text(size = 14))+
#     scale_color_manual(values = c("0.1" = "#000000", "1.5" = "#E69F00", "6" = "#56B4E9", "9" = "#009E73", "20" = "#F0E442"))



  
```

## YSI 

```{r}
#set up data
levels_distances <- c("Stream", "Pool 1", "Pool 2", "Pool 3", "Pool 4", "Cove A", "Cove B", "Site 50")

ysi <- read.csv("./ccr_2023_YSI.csv")

##SMB
# ysi |> 
#   mutate(DateTime = mdy_hm(DateTime),
#          DateTime = as.Date(DateTime)) |> 
#   select(-Notes) |> 
#   pivot_longer(-c(1:5)) |> 
#   filter(name %in% c("Temp_C", "DO_mgL", "SpCond_uScm")) |> 
#   filter(Site_EEM %in% c(30,301,300,299,298,3000)) |> 
#   #filter(Site_EEM %in% c(50,3,30,300,3000)) |> 
#   mutate(Distance = ifelse(Site_EEM == 3000, "Stream", NA),
#         Distance = ifelse(Site_EEM == 301, "Pool 1", Distance),
#         Distance = ifelse(Site_EEM == 300, "Pool 2", Distance),
#         Distance = ifelse(Site_EEM == 299, "Pool 3", Distance),
#         Distance = ifelse(Site_EEM == 298, "Pool 4", Distance),
#         Distance = ifelse(Site_EEM == 30, "Cove A", Distance),
#         Distance = ifelse(Site_EEM == 3, "Cove B", Distance),
#         Distance = ifelse(Site_EEM == 50, "Site 50", Distance)
#          ) |>  
#   ggplot(aes(x = factor(Distance, level = levels_distances), y = value, color = Depth_m))+
#   geom_point()+
#   facet_grid(name~DateTime, scales = "free_y")+
#   ggtitle("SMB")+
#   theme_bw() 


##HPB
# ysi |> 
#   mutate(DateTime = mdy_hm(DateTime),
#          DateTime = as.Date(DateTime)) |> 
#   select(-Notes) |> 
#   pivot_longer(-c(1:5)) |> 
#   filter(name %in% c("Temp_C", "DO_mgL", "SpCond_uScm")) |>  #, "DO_mgL", "SpCond_uScm"
#   #filter(Site_EEM %in% c(10,100,1000)) |> 
#   filter(Site_EEM %in% c(50,1,10,100,1000)) |> 
#   mutate(Distance = ifelse(Site_EEM == 1000, "Stream", NA),
#         Distance = ifelse(Site_EEM == 100, "Pool 1", Distance),
#         Distance = ifelse(Site_EEM == 10, "Cove A", Distance),
#         Distance = ifelse(Site_EEM == 1, "Cove B", Distance),
#         Distance = ifelse(Site_EEM == 50, "Site 50", Distance)
#          ) |>  
#   ggplot(aes(x = factor(Distance, level = levels_distances), y = value, color = Depth_m))+
#   geom_point()+
#   facet_grid(name~DateTime, scales = "free_y")+
#   labs(title = "HPB", y = "Temp (C)", x = "Site")+
#   theme_bw()+ theme(legend.position = "top", text = element_text(size = 14))+
#   scale_color_gradient("Depth_m",  high = "red", low = "blue") 


# ysi |> 
#   mutate(DateTime = mdy_hm(DateTime),
#          DateTime = as.Date(DateTime)) |> 
#   select(-Notes) |> 
#   pivot_longer(-c(1:5)) |> 
#   filter(name == "Temp_C") |> 
#   # filter(name %in% c("Temp_C", "DO_mgL", "SpCond_uScm")) |> 
#   #filter(Site_EEM %in% c(10,100,1000)) |> 
#   filter(Site_EEM %in% c(50,1,10,100,1000)) |> 
#   mutate(Distance = ifelse(Site_EEM == 1000, 0, NA),
#         Distance = ifelse(Site_EEM == 100, 150, Distance), #130-170, unsure on exact point
#         Distance = ifelse(Site_EEM == 10, 300, Distance), 
#         Distance = ifelse(Site_EEM == 1, 770, Distance), 
#         Distance = ifelse(Site_EEM == 50, 1460, Distance)
#          ) |>
#   ggplot(aes(x = Distance, y = value, color = Depth_m))+
#   geom_point()+
#   facet_grid(name~DateTime, scales = "free_y")+
#   ggtitle("HPB")+
#   theme_bw()+ theme(legend.position = "top", text = element_text(size = 14))+
#   scale_color_gradient("Depth_m",  high = "deepskyblue", low = "red") 

ysi |> 
  mutate(DateTime = mdy_hm(DateTime),
         DateTime = as.Date(DateTime)) |> 
  select(-Notes) |> 
  pivot_longer(-c(1:5)) |> 
  filter(name %in% c("Temp_C", "DO_mgL", "SpCond_uScm")) |>  #, "DO_mgL", "SpCond_uScm"
  #filter(Site_EEM %in% c(10,100,1000)) |> 
  filter(Site_EEM %in% c(50,1,10,100,1000)) |> 
  mutate(Distance = ifelse(Site_EEM == 1000, "Stream", NA),
        Distance = ifelse(Site_EEM == 100, "Pool 1", Distance),
        Distance = ifelse(Site_EEM == 10, "Cove A", Distance),
        Distance = ifelse(Site_EEM == 1, "Cove B", Distance),
        Distance = ifelse(Site_EEM == 50, "Site 50", Distance)
         ) |>  
  ggplot(aes(x = factor(Distance, level = levels_distances), y = value, color = Depth_m))+
  geom_point()+
  facet_grid(name~DateTime, scales = "free_y")+
  labs(title = "HPB", y = "Temp (C)", x = "Site")+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 14))+
  scale_color_gradient("Depth_m",  high = "red", low = "blue") 
  

```

## EEMs and YSI plot 

```{r}
#set up data
eems_hpb_cove <- eems_cove |> 
  mutate(Date = mdy(Date)) |> 
  filter(Date > ymd("2023-05-08"),
         Date < ymd("2023-08-08")) |> 
  select(1:6, HIX, BIX, Cl_ugL, DOC_mgL) |> 
  filter(Site_num %in% c(50, 1, 10,100,1000)) |> 
  pivot_longer(-c(1:6)) |> 
  select(Site_num, Date, Depth_m, name, value)

eems_hpb_ysi <- ysi |> 
  mutate(DateTime = mdy_hm(DateTime),
         DateTime = as.Date(DateTime)) |> 
    filter(Site_EEM %in% c(50, 1, 10,100,1000)) |> 
  select(-Notes) |> 
  pivot_longer(-c(1:5)) |> 
  filter(name %in% c("Temp_C", "DO_mgL", "SpCond_uScm")) |> 
  rename(Site_num = Site_EEM,
         Date = DateTime) |> 
  select(Site_num, Date, Depth_m, name, value)

##plot
levels_distances <- c("Stream", "Pool", "Cove A", "Cove B", "Dam")

depths <- c(0.1, 0.5, 1, 6, 9, 20)

rbind(eems_hpb_cove, eems_hpb_ysi) |> 
 mutate(Distance = ifelse(Site_num == 1000, "Stream", NA),
        Distance = ifelse(Site_num == 100, "Pool", Distance),
        Distance = ifelse(Site_num == 10, "Cove A", Distance),
        Distance = ifelse(Site_num == 1, "Cove B", Distance),
        Distance = ifelse(Site_num == 50, "Dam", Distance)
         ) |>
  mutate(Depth_m = ifelse(Depth_m == "SURF", 0.1, Depth_m),
         Depth_m = ifelse(Depth_m == "BOT", 0.4, Depth_m),
         Depth_m = ifelse(Depth_m == 19, 20, Depth_m),
         Depth_m = ifelse(Depth_m == 1.5, 1, Depth_m),
         Depth_m = ifelse(Depth_m == 0.4, 1, Depth_m)) |> 
  mutate(Depth_m = as.numeric(Depth_m)) |> 
  filter(Depth_m %in% depths,
         name %in% c("BIX", "HIX", "DOC_mgL", "Cl_ugL", "Temp_C")) |> 
ggplot(aes(x = factor(Distance, level = levels_distances), y = value, color = factor(Depth_m, levels = depths),
           group = factor(Depth_m, level = depths)))+ 
  geom_point(size = 2)+
  #geom_line()+
  facet_grid(factor(name, levels = c("BIX", "HIX", "DOC_mgL", "Cl_ugL", "Temp_C"))~Date, scales = "free_y")+
  labs(y = "value", x = "Site", color = "Depth (m)")+
  theme_bw()+ 
  theme(legend.position = "top", text = element_text(size = 16))+ guides(color = guide_legend(nrow = 1))+
  scale_color_manual(values = c("0.1" = "#000000",  "1" = "#E69F00", "6" = "#56B4E9", "9" = "#009E73", "20" = "#F0E442")) #"0.5" = "red",


```

## IC

```{r}
icdata <- read.csv("./EEMs_chem_2023_plungepoint.csv")
icdata <- replace(icdata, icdata =="n.a.", NA) #set values below detection to NA 

levels_distances_ic <- c("Stream", "Pool", "Cove A", "Cove B", "Site 50")

levels_depth <- c(0.1, 1.5, 6, 9, 20)

## grid variables SITE as factor 
icdata |> 
  mutate(Date = mdy(Date)) |> 
  filter(Date > ymd("2023-05-08"),
         Date < ymd("2023-08-08")) |> 
  select(1:6, Cl_ugL) |> 
  filter(Site_num %in% c(50,1,10,100,1000)) |> 
    pivot_longer(-c(1:6)) |> 
  mutate(Distance = ifelse(Site_num == 1000, "Stream", NA),
        Distance = ifelse(Site_num == 100, "Pool", Distance),
        Distance = ifelse(Site_num == 10, "Cove A", Distance),
        Distance = ifelse(Site_num == 1, "Cove B", Distance),
        Distance = ifelse(Site_num == 50, "Site 50", Distance)
         ) |>
  mutate(Depth_m = ifelse(Depth_m == "SURF", 0.1, Depth_m),
         Depth_m = ifelse(Depth_m %in% c("BOT", "PD"), 1.5, Depth_m)) |> 
  ggplot(aes(x = factor(Distance, level = levels_distances_ic), y = value, color = factor(Depth_m, levels = levels_depth)))+ 
  geom_point()+
  facet_grid(factor(name)~Date, scales = "free_y")+ #name, , levels = c("BIX", "HIX", "DOC_mgL")
  labs(y = "value", x = "Site", title = "HPB", color = "Depth (m)")+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 14))+
    scale_color_manual(values = c("0.1" = "#000000", "1.5" = "#E69F00", "6" = "#56B4E9", "9" = "#009E73", "20" = "#F0E442"))



icdata |> 
  mutate(Date = mdy(Date)) |> 
  filter(Date > ymd("2023-05-08"),
         Date < ymd("2023-08-08")) |> 
  select(1:6, Cl_ugL) |> 
  filter(Site_num %in% c(50,3,30,300,3000)) |> 
    pivot_longer(-c(1:6)) |> 
  mutate(Distance = ifelse(Site_num == 3000, "Stream", NA),
        Distance = ifelse(Site_num == 300, "Pool", Distance),
        Distance = ifelse(Site_num == 30, "Cove A", Distance),
        Distance = ifelse(Site_num == 3, "Cove B", Distance),
        Distance = ifelse(Site_num == 50, "Site 50", Distance)
         ) |>
  mutate(Depth_m = ifelse(Depth_m == "SURF", 0.1, Depth_m),
         Depth_m = ifelse(Depth_m %in% c("BOT", "PD"), 1.5, Depth_m)) |> 
  ggplot(aes(x = factor(Distance, level = levels_distances_ic), y = value, color = factor(Depth_m, levels = levels_depth)))+ 
  geom_point()+
  facet_grid(factor(name)~Date, scales = "free_y")+ #name, , levels = c("BIX", "HIX", "DOC_mgL")
  labs(y = "value", x = "Site", title = "SMB", color = "Depth (m)")+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 14))+
    scale_color_manual(values = c("0.1" = "#000000", "1.5" = "#E69F00", "6" = "#56B4E9", "9" = "#009E73", "20" = "#F0E442"))




```


## Discharge 

```{r}

q <- read_csv("https://pasta.lternet.edu/package/data/eml/edi/454/7/702d3b355854211a8dbb587094cfccb7")

q |> 
  filter(Reservoir == "CCR",
         year(DateTime) == 2023)  |> 
  mutate(Site = ifelse(Site == 301, 300, Site)) |> 
  ggplot(aes(x = DateTime, y = Flow_cms, color = as.factor(Site)))+
  geom_line()+
  geom_point()+
  theme_classic() + theme(text = element_text(size = 14))
  

q |> 
  filter(Reservoir == "CCR",
         Site %in% c(300,301, 100, 101))  |> 
  mutate(Site = ifelse(Site == 301, 300, Site),
         Site = ifelse(Site == 101, 100, Site)) |> 
  ggplot(aes(x = DateTime, y = Flow_cms, color = as.factor(Site)))+
  geom_line()+
  geom_point()+
  ylim(0,0.25)+
  theme_classic() + theme(text = element_text(size = 14))


```

## Precip 

```{r}
ccr_met <- read_csv("https://pasta.lternet.edu/package/data/eml/edi/1105/2/5c9281623ab7676ca1be85ee1761bf28")

# ccr_met_git <- read_csv("https://raw.githubusercontent.com/FLARE-forecast/CCRE-data/ccre-dam-data/ccre-met.csv", skip = 1) |> dplyr::slice(-c(1:2))

#### rain 2023
ccr_met |> 
  filter(year(DateTime) == 2023) |> 
  mutate(Date = as.Date(DateTime)) |> 
  filter(Date > ymd("2023-05-01"),
         Date < ymd("2023-08-01")) |>
  group_by(Date) |> 
  summarize(daily_precip = sum(Rain_Total_mm)) |> 
  ggplot(aes(x = Date, y = daily_precip))+
  geom_point()+
  #geom_line()+
  ylim(0,50)+
  labs(x = "Date", y = "Total Rain (mm)")+
  geom_vline(xintercept = c( ymd("2023-06-01"), ymd("2023-06-30")), linewidth = 1, linetype = 2)+
  theme_classic() + theme(text = element_text(size = 16))

#### bar pressure
# ROA elevation: 346.7m; CCR dam elevation: 356.6 based on bathy


#roa met from 1 - 3 apr 24
# roa_noaa_4apr <- read.csv("C:/Users/dwh18/Downloads/ROA_met_4apr24.csv") |> 
#   mutate(DateTime = paste("2024-04-", Date, " ", Time, sep = ""),
#          DateTime = ymd_hm(DateTime))

#roa met 2023
roa_noaa_2023 <- read.csv("C:/Users/dwh18/Downloads/ROA_2023_local_met.csv") |> 
  mutate(DateTime = gsub("T", " ", DATE),
         DateTime = ymd_hms(DateTime)) |> 
  select(DateTime, everything()) |> 
  filter(REPORT_TYPE == "FM-15") |>  #code for routine hourly weather conditoin at air terminals
    mutate(Date = as.Date(DateTime)) |>
    filter(Date > ymd("2023-05-01"),
         Date < ymd("2023-08-01"))


##ccr met vs roa 2023
ccr_met |> 
  filter(year(DateTime) == 2023) |>
  mutate(Date = as.Date(DateTime),
         DateTime = ymd_hms(DateTime),
         BP_inHg = BP_Average_kPa*0.2953) |>
      filter(Date > ymd("2023-05-01"),
         Date < ymd("2023-08-01")) |>
  ggplot(aes(x = DateTime, y = BP_inHg, color = "CCR met"))+
  geom_point()+
  geom_point(data = roa_noaa_2023, aes(x= DateTime, y = HourlyStationPressure, color = "ROA met"))+
  labs(x = "Date", y = "BP (inHg)", title = "CCR vs ROA Barometric Pressure")+
  theme_classic() + theme(text = element_text(size = 16))


## ccr met vs roa april 2024
# ccr_met_git |> 
#   #filter(year(DateTime) == 2023) |>
#   rename(DateTime = TIMESTAMP) |> 
#   mutate(Date = as.Date(DateTime),
#          DateTime = ymd_hms(DateTime),
#          BP_kPa_Avg = as.numeric(BP_kPa_Avg),
#          BP_inHg = BP_kPa_Avg*0.2953) |>
#   filter(Date > ymd("2024-03-31")
#          #Date < ymd("2023-06-10")
#          ) |>
#   # group_by(Date) |> 
#   # summarize(BP_Average_kPa = mean(BP_Average_kPa, na.rm = T)) |> 
#   ggplot(aes(x = DateTime, y = BP_inHg, color = "CCR met"))+
#   geom_point()+
#   geom_point(data = roa_noaa_4apr, aes(x= DateTime, y = BP_inHg, color = "ROA met"))+
#   #geom_line()+
#   labs(x = "Date", y = "BP (inHg)", title = "CCR vs ROA Barometric Pressure")+
#   theme_classic() + theme(text = element_text(size = 16))



```


## Chl-a from dam

```{r}
ccr_dam <- read_csv("https://pasta.lternet.edu/package/data/eml/edi/1069/2/ea78dd541e089687af1f4c4b550bc9ca")

ccr_dam |> 
  filter(year(DateTime) == 2023) |> 
  mutate(Date = as.Date(DateTime)) |> 
  filter(Date > ymd("2023-05-01"),
         Date < ymd("2023-08-01")) |>
  group_by(Date) |> 
  summarize(daily_chla = mean(EXOChla_ugL_1, na.rm = T)) |> 
  ggplot(aes(x = Date, y = daily_chla))+
  geom_point()+
  geom_line()+
  labs(x = "Date", y = "Chlorophyll-a (ug/L)")+
  geom_vline(xintercept = c(ymd("2023-06-01"), ymd("2023-06-30")), linewidth = 1, linetype = 2)+
  theme_classic() + theme(text = element_text(size = 14))

```





