---
title: "CCR Spatial chemistry"
author: "Dexter Howard"
date: "2024-06-20"
output: html_document
---

## Read in packages 

```{r, include = F}
library(tidyverse)
# library(scales) #for date format on plots
# library(patchwork) #arrange figures w/ slashes and lines
# library(plotly)

Site_code_number <- data.frame(Site_code = c("CS1", "CS2", "CP1", "CP2", "CC1", "CC2", "CC3", "CC4", "C50",
                                             "B50", "F50", "F100"),
                               Site_number = c(101, 100, 98, 96, 94, 92, 90, 88, 50, 50,50,100))

## bring in distances and site class table from google sheets; have to redownload locally each time 
distances <- read.csv("C:/Users/dwh18/Downloads/2024 spatial sampling - Distances (2).csv") |> 
  mutate(Date = mdy(Date)) |> 
  dplyr::select(-c(13,14)) |> 
  pivot_longer(-c(1,11,12), names_to = "Site_code", values_to = "Distance_ft") |> 
  filter(!Site_code == "C1") 


site_class <- read.csv("C:/Users/dwh18/Downloads/2024 spatial sampling - Sites_Class (2).csv") |> 
  dplyr::select(-X, -Key) |> 
  mutate(Date = mdy(Date)) |> 
  pivot_longer(-c(1), names_to = "Site_code", values_to = "Site_Class") |> 
  mutate(Site_Class = ifelse(Site_Class %in% c("S", "S "), "Stream", Site_Class),
         Site_Class = ifelse(Site_Class %in% c("P", "P "), "Pool", Site_Class),
         Site_Class = ifelse(Site_Class == "C", "Cove", Site_Class),
         Site_Class = ifelse(Site_Class == "L", "Pelagic", Site_Class))


```

## Read in A lab chem



```{r}

ccr_solubles <- read_csv("C:/Users/dwh18/OneDrive/Desktop/Alab_QAQC/EDI2025/Solubles_DOC_joined_v2.csv") |>
  filter(Reservoir == "CCR") |> 
  mutate(Date = mdy(Date),
         Site_code = ifelse(Site == 101, "S1", NA),
         Site_code = ifelse(Site == 100, "S2", Site_code),
         Site_code = ifelse(Site == 98, "P1", Site_code),
         Site_code = ifelse(Site == 96, "P2", Site_code),
         Site_code = ifelse(Site == 94, "C1", Site_code),
         Site_code = ifelse(Site == 92, "C2", Site_code),
         Site_code = ifelse(Site == 90, "C3", Site_code),
         Site_code = ifelse(Site == 88, "C4", Site_code),
         Site_code = ifelse(Site == 50, "C50", Site_code))


solubles_plotting <- left_join(ccr_solubles, distances, by = c("Site_code", "Date")) |> 
  left_join(site_class, by = c("Site_code", "Date")) |> 
  mutate(Distance = Distance_ft*0.3048,
         Dry_start = Dry_start*0.3048,
         Dry_end = Dry_end*0.3048) |> 
  filter(!Date %in% c(ymd("2024-07-31"), ymd("2024-08-01"))) |> 
  select(Reservoir, Site, Site_code, Site_Class, Depth_m, Date, Rep, Distance, Dry_start, Dry_end, TOC, NO3, NH4, PO4) |> 
  rename(DOC = TOC)


```


TESTS

```{r}

solubles_plotting |> 
  ggplot(aes(x = Date, y = DOC, color = Run_date))+
  geom_point()+
  facet_grid(Reservoir~Site)



```




plot it! 

```{r}
#summarize
## something going wrong in here
solubles_summary <- solubles_plotting |>
  filter(Reservoir == 'CCR') |> 
  select(Site, Site_Class, Depth_m, Date, Distance, Dry_start, Dry_end, DOC, NO3, NH4, PO4) |>
  group_by(Site, Site_Class, Depth_m, Date, Dry_start, Dry_end, Distance) |>
  summarise(DOC_mean = mean(DOC, na.rm = T),
            DOC_min = min(DOC, na.rm = T),
            DOC_max = max(DOC, na.rm = T),
            PO4_mean = mean(PO4, na.rm = T),
            PO4_min = min(PO4, na.rm = T),
            PO4_max = max(PO4, na.rm = T),
            NH4_mean = mean(NH4, na.rm = T),
            NH4_min = min(NH4, na.rm = T),
            NH4_max = max(NH4, na.rm = T),
            NO3_mean = mean(NO3, na.rm = T),
            NO3_min = min(NO3, na.rm = T),
            NO3_max = max(NO3, na.rm = T)
                        ) |>
  mutate(Rep = ifelse(DOC_mean != DOC_min, "Y", "N")) |> 
  mutate(Site = as.numeric(Site))


#check missing samples 
z <- arrange(solubles_plotting, Date, desc(Site), Depth_m) 

zz <- arrange(solubles_summary, Date, desc(Site), Depth_m) 



#### Rep check
solubles_summary |> 
  filter(Rep == "Y") |> ggplot(aes(y = Depth_m, x= DOC_mean))+
  geom_point(size = 1) +    geom_errorbar(aes(xmin = DOC_min, xmax = DOC_max),    width = 2 )+
  facet_grid(Site~Date) + labs(title = "DOC reps")

solubles_summary |> 
  filter(Rep == "Y") |> ggplot(aes(y = Depth_m, x= PO4_mean))+
  geom_point(size = 1) +    geom_errorbar(aes(xmin = PO4_min, xmax = PO4_max),    width = 2 )+
  facet_grid(Site~Date) + labs(title = "PO4 reps")


#### PLOT

##DOC
solubles_summary |> 
  #filter(!Site == 50) |> 
  ggplot(aes(x = Distance, y = DOC_mean, fill = Depth_m,
             shape = factor(Site_Class, levels = c("Stream", "Pool", "Cove", "Pelagic"))))+
  geom_point(size = 3) + 
  geom_errorbar(aes(ymin = DOC_min, ymax = DOC_max), width = 2) +
  facet_wrap(~Date, scales = "fixed", ncol = 4)+ 
  geom_rect(aes(xmin = Dry_start, xmax = Dry_end, ymin = -Inf, ymax = Inf), alpha = 0.01, fill = "gray", color = NA )+ 
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
    labs(y = "DOC (mg/L)", x= "Distance from Stream (m)",  shape = "Site Type")+
  scale_x_continuous(breaks = c(0, 500, 1000, 1500))+ #c(250, 750)
  scale_shape_manual(values = c(24, 22, 21, 25))+ #18, 15, 16, 17
  scale_fill_gradient2(low = "red",  high ="blue",
                       midpoint = 9,  guide = "colourbar", breaks = c(3,6,9, 15, 20))

    #across dates
solubles_summary |> 
  ggplot(aes(x = Distance, y = DOC_mean, fill = Depth_m ))+
  geom_smooth()+
  geom_point(shape = 21, size = 3) + 
  geom_errorbar(aes(ymin = DOC_min, ymax = DOC_max), width = 2) +
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x= "Distance from Stream (m)",  fill = "Depth (m)", y = "DOC (mg/L)")+
  scale_x_continuous(breaks = c(0, 500, 1000, 1500))+  
  scale_fill_gradient2(low = "red",  high ="blue",
                       midpoint = 6,  guide = "colourbar", breaks = c(3,6,9, 15, 20))

##PO4
solubles_summary |> 
  #filter(!Site == 50) |> 
  ggplot(aes(x = Distance, y = PO4_mean, fill = Depth_m,
             shape = factor(Site_Class, levels = c("Stream", "Pool", "Cove", "Pelagic"))))+
  geom_point() + 
  geom_errorbar(aes(ymin = PO4_min, ymax = PO4_max), width = 2) +
  facet_wrap(~Date, scales = "fixed", ncol = 4)+ 
  geom_rect(aes(xmin = Dry_start, xmax = Dry_end, ymin = -Inf, ymax = Inf), alpha = 0.01, fill = "gray", color = NA )+ 
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
    labs(y = "PO4 (ug/L)", x= "Distance from Stream (m)",  shape = "Site Type")+
  scale_x_continuous(breaks = c(0, 500, 1000, 1500))+ #c(250, 750)
  scale_shape_manual(values = c(24, 22, 21, 25))+ #18, 15, 16, 17
  scale_fill_gradient2(low = "red",  high ="blue",
                       midpoint = 9,  guide = "colourbar", breaks = c(3,6,9, 15, 20))


##NO3
solubles_summary |> 
  #filter(!Site == 50) |> 
  ggplot(aes(x = Distance, y = NO3_mean, fill = Depth_m,
             shape = factor(Site_Class, levels = c("Stream", "Pool", "Cove", "Pelagic"))))+
  geom_point() + 
  geom_errorbar(aes(ymin = NO3_min, ymax = NO3_max), width = 2) +
  facet_wrap(~Date, scales = "fixed", ncol = 4)+ 
  geom_rect(aes(xmin = Dry_start, xmax = Dry_end, ymin = -Inf, ymax = Inf), alpha = 0.01, fill = "gray", color = NA )+ 
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
    labs(y = "NO3 (ug/L)", x= "Distance from Stream (m)",  shape = "Site Type")+
  scale_x_continuous(breaks = c(0, 500, 1000, 1500))+ #c(250, 750)
  scale_shape_manual(values = c(24, 22, 21, 25))+ #18, 15, 16, 17
  scale_fill_gradient2(low = "red",  high ="blue",
                       midpoint = 9,  guide = "colourbar", breaks = c(3,6,9, 15, 20))

##NH4
solubles_summary |> 
  #filter(!Site == 50) |> 
  ggplot(aes(x = Distance, y = NH4_mean, fill = Depth_m,
             shape = factor(Site_Class, levels = c("Stream", "Pool", "Cove", "Pelagic"))))+
  geom_point() + 
  geom_errorbar(aes(ymin = NH4_min, ymax = NH4_max), width = 2) +
  facet_wrap(~Date, scales = "fixed", ncol = 4)+ 
  geom_rect(aes(xmin = Dry_start, xmax = Dry_end, ymin = -Inf, ymax = Inf), alpha = 0.01, fill = "gray", color = NA )+ 
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
    labs(y = "NH4 (ug/L)", x= "Distance from Stream (m)",  shape = "Site Type")+
  scale_x_continuous(breaks = c(0, 500, 1000, 1500))+ #c(250, 750)
  scale_shape_manual(values = c(24, 22, 21, 25))+ #18, 15, 16, 17
  scale_fill_gradient2(low = "red",  high ="blue",
                       midpoint = 9,  guide = "colourbar", breaks = c(3,6,9, 15, 20))



# ##trying virdis
# solubles_summary |> 
#   #filter(!Site == 50) |> 
#   ggplot(aes(x = Distance, y = DOC_mean, fill = Depth_m, #fill = Depth_m,
#              shape = factor(Site_Class, levels = c("Stream", "Pool", "Cove", "Pelagic"))))+
#   geom_point() + 
#   geom_errorbar(aes(ymin = DOC_min, ymax = DOC_max), width = 2) +
#   facet_wrap(~Date, scales = "fixed", ncol = 4)+ 
#   geom_rect(aes(xmin = Dry_start, xmax = Dry_end, ymin = -Inf, ymax = Inf), alpha = 0.01, fill = "gray", color = NA )+ 
#   theme_bw()+ theme(legend.position = "top", text = element_text(size = 18))+
#     labs(x= "Distance from Stream (m)",  shape = "Site Type")+
#   scale_shape_manual(values = c(24, 22, 21, 25))+ #18, 15, 16, 17
#   scale_fill_viridis_c(breaks = c(3,6,9,12, 15,18))
#   scale_color_gradient(high = "#CFCFCF", low = "black", breaks = c(3,6,9,12))+  scale_fill_gradient(high = "#CFCFCF", low = "black",  breaks = c(3,6,9,12)) 


```



## Read in EEMs

Get EEM data 

```{r}

## EEM data
eems24 <- read.csv("../EEMs_Results_2024.csv")

zz <- arrange(eems24, mdy(Date), desc(Site), Depth_m)


eems <- eems24 |> 
    mutate(Date = mdy(Date),
           Date = ifelse(Date == ymd("2024-08-15"), ymd("2024-08-14"), Date),
           Date = ifelse(Date == ymd("2025-02-17"), ymd("2025-02-26"), Date),
           Date = as.Date(Date),
           Site_code = ifelse(Site == 101, "S1", NA),
         Site_code = ifelse(Site == 100, "S2", Site_code),
         Site_code = ifelse(Site == 98, "P1", Site_code),
         Site_code = ifelse(Site == 96, "P2", Site_code),
         Site_code = ifelse(Site == 94, "C1", Site_code),
         Site_code = ifelse(Site == 92, "C2", Site_code),
         Site_code = ifelse(Site == 90, "C3", Site_code),
         Site_code = ifelse(Site == 88, "C4", Site_code),
         Site_code = ifelse(Site == 50, "C50", Site_code)
         ) |> 
  dplyr::select(Reservoir, Site, Site_code, Depth_m, Date, FI., HIX., BIX., T., A., A.T., a254, a350, A254, A350, NOTES)


eems_plotting <- left_join(eems, distances, by = c("Site_code", "Date")) |> 
  left_join(site_class, by = c("Site_code", "Date")) |> 
  mutate(Distance = Distance_ft*0.3048,
         Dry_start = Dry_start*0.3048,
         Dry_end = Dry_end*0.3048) |> 
  filter(!Date %in% c(ymd("2024-07-31"), ymd("2024-08-01"))) |> 
  dplyr::select(Reservoir, Site, Site_code, Site_Class, Depth_m, Date, Distance, Dry_start, Dry_end, FI., HIX., BIX., T., A., A.T., a254, a350, NOTES)


eems_plotting

```

Multi eems metrics
```{r}
#across dates
eems_plotting |> 
  dplyr::select(-NOTES) |> 
  pivot_longer(-c(1:9)) |> 
  ggplot(aes(x = Distance, y = value, fill = Depth_m
             ))+
  geom_point(shape = 21, size = 3) + 
  facet_wrap(~name, scales = "free_y")+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x= "Distance from Stream (m)",  fill = "Depth (m)", y = "HIX")+
  scale_x_continuous(breaks = c(0, 500, 1000, 1500))+  
  scale_fill_gradient2(low = "red",  high ="blue",
                       midpoint = 6,  guide = "colourbar", breaks = c(3,6,9, 15, 20))

#by date
eems_plotting |> 
  dplyr::select(-NOTES) |> 
  pivot_longer(-c(1:9)) |> 
  ggplot(aes(x = Distance, y = value, fill = Depth_m
             ))+
  geom_point(shape = 21, size = 3) + 
  facet_grid(name~Date, scales = "free_y")+
  geom_rect(aes(xmin = Dry_start, xmax = Dry_end, ymin = -Inf, ymax = Inf), 
           alpha = 0.01, fill = "gray", color = NA )+ #color gets rid of border
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x= "Distance from Stream (m)",  fill = "Depth (m)", y = "HIX")+
  scale_x_continuous(breaks = c(0, 500, 1000, 1500))+  
  scale_fill_gradient2(low = "red",  high ="blue",
                       midpoint = 6,  guide = "colourbar", breaks = c(3,6,9, 15, 20))





```


## Rep checks 

```{r}
#summarize data 
eems_summary <- eems_plotting |> 
  filter(!NOTES %in% c("PART", "FRIDGE_TEST")) |> 
  filter(Site_code != "C1") |> 
  rename(HIX = HIX.,
         BIX = BIX.,
         FI = FI.,
         A = A.,
         peakT = T.,
         AT = A.T.) |>  #### can just change the rename here for what value you want to look at
  dplyr::select(Site, Site_Class, Depth_m, Date, Distance, Dry_start, Dry_end, HIX, BIX, FI, A, peakT, AT) |> 
  group_by(Site, Site_Class, Depth_m, Date, Dry_start, Dry_end, Distance) |> 
  summarise(HIX_mean = mean(HIX, na.rm = T),
            HIX_min = min(HIX, na.rm = T),
            HIX_max = max(HIX, na.rm = T),
            BIX_mean = mean(BIX, na.rm = T),
            BIX_min = min(BIX, na.rm = T),
            BIX_max = max(BIX, na.rm = T),
            FI_mean = mean(FI, na.rm = T),
            A_mean = mean(A, na.rm = T),
            T_mean = mean(peakT, na.rm = T),
            AT_mean = mean(AT, na.rm = T)
            ) |> 
  mutate(Rep = ifelse(HIX_mean != HIX_min, "Y", "N"))

zzz <- arrange(eems_summary, Date, desc(Site), Depth_m)



#plot w/ error bars
eems_summary |> 
  ggplot(aes(x = Distance, y = HIX_mean, color = Depth_m)) +
  geom_point(size = 1) +  # Plot the mean values as points
  geom_errorbar(
    aes(ymin = HIX_min, ymax = HIX_max),
    width = 2  # Width of the error bars
  ) +
  facet_wrap(~Date, nrow = 4)+
  theme_bw()

#by site and date
eems_summary |> 
  filter(Rep == "Y") |> 
  ggplot(aes(y = Depth_m, x= HIX_mean))+
  geom_point(size = 1) +  
  geom_errorbar(
    aes(xmin = HIX_min, xmax = HIX_max),
    width = 2 )+
  # xlim(3,6)+
  facet_grid(Site~Date)
  


```

fridge test 

```{r}

eemsfridge <- read.csv("../Processed_Data/Fridge_test_data.csv")

eemsfridge |> 
  ggplot(aes(x = test_code, y = FI., color = as.factor(Depth_m), shape = as.factor(Site_number)))+
  geom_point()

```




## DWH exploration

put sensors, eems, and hydrology all together
```{r}
head(eems_summary)
head(solubles_summary)
head(CCR_usgs_data)
head(waterlevel_precip)
head(sensors)

# data <- eems_summary

chemjoin <- full_join(eems_summary, solubles_summary, by = c("Site", "Site_Class", "Depth_m", "Date", "Distance"))


data2 <- plyr::rbind.fill(chemjoin, sensors) |> 
    mutate(SpCond_uScm = ifelse(SpCond_uScm > 200, NA, SpCond_uScm) ) 


data2_hydro <- left_join(data2, CCR_usgs_data, by = "Date")


```

just 0.1m 

```{r}
#previous
 data2 |> 
  select(Site, Date, Depth_m, Site_Class, Distance, Dry_start, Dry_end, 
          DOC_mean, HIX_mean) |> 
  rename(DOC_mgL = DOC_mean, HIX = HIX_mean) |> 
  pivot_longer(-c(1:7)) |> 
  ggplot(aes(x = Distance, y = value, fill = Depth_m       ))+
  facet_wrap(~name, nrow = 1, scales = "free_y")+
  geom_point(shape = 21, size = 4)+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 15),
                    legend.text = element_text(size=15),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x= "Distance from Stream (m)", fill = "Depth (m)",
       shape = "Site Type")+
  scale_x_continuous(breaks = c(0, 500, 1000, 1500))+ #c(250, 750)
    # scale_fill_gradient2(low = "#C0504D", mid = "#4f81BD",  high ="#17375E", #these are the powerpoint colors
    #                    midpoint = 15,  guide = "colourbar", breaks = c(3,6,9, 15))
  scale_fill_gradient2(low = "red",  high ="blue",
                       midpoint = 6,  guide = "colourbar", breaks = c(3,6,9, 15, 20))


#just 0.1
 data2 |> 
  select(Site, Date, Depth_m, Site_Class, Distance, Dry_start, Dry_end, 
          DOC_mean, HIX_mean) |> 
  filter(Depth_m == 0.1) |> 
  rename(DOC_mgL = DOC_mean, HIX = HIX_mean) |> 
  pivot_longer(-c(1:7)) |> 
  ggplot(aes(x = Distance, y = value, fill = Depth_m))+
  facet_wrap(~name, nrow = 1, scales = "free_y")+
  geom_point(shape = 21, size = 4)+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 15),
                    legend.text = element_text(size=15),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x= "Distance from Stream (m)", fill = "Depth (m)",
       shape = "Site Type")+
  scale_x_continuous(breaks = c(0, 500, 1000, 1500))+ #c(250, 750)
  scale_fill_gradient2(low = "red",  high ="blue",
                       midpoint = 6,  guide = "colourbar", breaks = c(3,6,9, 15, 20))
 
 
 ##by hydro
 data2_hydro |> 
     select(Site, Date, Depth_m, CCR_Dam_depth_m, USGS_TinkerCreek_dailystage_ft, Site_Class, Distance, Dry_start, Dry_end, 
          DOC_mean, HIX_mean) |> 
  rename(DOC_mgL = DOC_mean, HIX = HIX_mean) |> 
  pivot_longer(-c(1:9)) |> 
  ggplot(aes(x = Distance, y = value, fill = USGS_TinkerCreek_dailystage_ft       ))+
  facet_wrap(~name, nrow = 1, scales = "free_y")+
  geom_point(shape = 21, size = 4)+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 15),
                    legend.text = element_text(size=15),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x= "Distance from Stream (m)", 
       shape = "Site Type")+
  scale_x_continuous(breaks = c(0, 500, 1000, 1500))
 
 
 ##by hydro
 data2_hydro |> 
     select(Site, Date, Depth_m, CCR_Dam_depth_m, USGS_TinkerCreek_dailystage_ft, Site_Class, Distance, Dry_start, Dry_end, 
          DOC_mean, HIX_mean) |> 
  rename(DOC_mgL = DOC_mean, HIX = HIX_mean) |> 
  pivot_longer(-c(1:9)) |> 
   left_join(Dry_distance, by = "Date") |> 
  ggplot(aes(x = Distance, y = value, fill = Dry_distance       ))+
  facet_wrap(~name, nrow = 1, scales = "free_y")+
  geom_point(shape = 21, size = 4)+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 15),
                    legend.text = element_text(size=15),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x= "Distance from Stream (m)", 
       shape = "Site Type")+
  scale_x_continuous(breaks = c(0, 500, 1000, 1500))

```



exploration re WMWs comments 

```{r}
######### look at thermistor strat
# ccr_L1 <- read_csv("https://raw.githubusercontent.com/FLARE-forecast/CCRE-data/ccre-dam-data-qaqc/ccre-waterquality_L1.csv")
# ccr_edi <- read_csv("https://pasta.lternet.edu/package/data/eml/edi/1069/3/4afb209b30ebed898334badd3819d854")
# ccrfull <- rbind(ccr_edi, ccr_L1)
# 
# thermistors <- ccrfull |> 
#   select(3:16) |> 
#   filter(DateTime > ymd_hms("2024-04-15 00:00:00")) |> 
#   pivot_longer(-1) |> 
#   ggplot(aes(x= DateTime, y = value, color = name))+
#   geom_line()+ geom_vline(xintercept = ymd_hms("2024-05-22 00:00:00"))+ geom_vline(xintercept = ymd_hms("2024-06-19 00:00:00"))+ geom_vline(xintercept = ymd_hms("2024-07-11 00:00:00"))+ geom_vline(xintercept = ymd_hms("2024-08-14 00:00:00"))+ geom_vline(xintercept = ymd_hms("2024-09-16 00:00:00"))+ 
#       geom_vline(xintercept = ymd_hms("2024-09-30 00:00:00"))+  geom_vline(xintercept = ymd_hms("2024-10-28 00:00:00"))+  geom_vline(xintercept = ymd_hms("2024-12-17 00:00:00"))+  geom_vline(xintercept = ymd_hms("2025-02-26 00:00:00"))
# 
# thermistors
# plotly::ggplotly(thermistors)

# ccr_dam |> 
#   filter(DateTime > ymd("2024-05-01")) |> 
#   mutate(Date = as.Date(DateTime)) |> 
#   group_by(Date) |> 
#   summarise(chla = mean(EXOChla_ugL_1, na.rm = T)) |> 
#   ggplot(aes(x = Date, y = chla))+geom_point() +
#   scale_x_date(date_breaks = "1 month", date_labels = "%b")


```


```{r}

## EEMs and DOC
chemjoin |> 
  ungroup() |> 
    select(Site, Depth_m, Date, Distance, HIX_mean, BIX_mean, DOC_mean) |> 
  # select(Site, Depth_m, Date, Distance, HIX_mean, BIX_mean, DOC_mean, FI_mean, A_mean, T_mean, AT_mean) |> 
  pivot_longer(-c(1:4)) |> 
  ggplot(aes(x = Distance, y = value, fill = Depth_m))+
  geom_point(shape = 21, size = 3) + #shape = 21,
  facet_grid(name~Date, scales = "free_y")+ theme_bw()+  theme(legend.position = "top", 
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  scale_fill_gradient2(low = "red",  high ="blue",
                       midpoint = 6,  guide = "colourbar", breaks = c(3,6,9, 15))


chemjoin |> 
  ungroup() |> 
    select(Site, Depth_m, Date, Distance, HIX_mean, BIX_mean, DOC_mean) |> 
  # select(Site, Depth_m, Date, Distance, HIX_mean, BIX_mean, DOC_mean, FI_mean, A_mean, T_mean, AT_mean) |> 
  pivot_longer(-c(1:4)) |> 
  ggplot(aes(x = Distance, y = value, fill = Depth_m))+
  geom_point(shape = 21, size = 3) + #shape = 21,
  facet_wrap(~name, scales = "free_y", ncol = 1)+ theme_bw()+  theme(legend.position = "top", 
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  scale_fill_gradient2(low = "red",  high ="blue",
                       midpoint = 6,  guide = "colourbar", breaks = c(3,6,9, 15))



### HIX ~ DOC ####
chemjoin |> 
   # filter(Date < ymd("2024-12-01")) |> 
  ggplot(aes(x = DOC_mean, y = HIX_mean, color = Depth_m))+
  geom_point() + #shape = 21,
  theme_bw()+ 
    labs(x= "DOC", y = "HIX")+
  scale_color_gradient2(low = "red",  high ="blue",
                       midpoint = 6,  guide = "colourbar", breaks = c(3,6,9, 15))

chemjoin |> 
   # filter(Date < ymd("2024-12-01")) |> 
  ggplot(aes(x = DOC_mean, y = HIX_mean, color = as.factor(Date)))+
  geom_point() + #shape = 21,
  theme_bw()+ 
    labs(x= "DOC", y = "HIX")


chemjoin |> 
   # filter(Date < ymd("2024-12-01")) |> 
  ggplot(aes(x = DOC_mean, y = HIX_mean, color = (Distance)))+
  geom_point() + #shape = 21,
  theme_bw()+ 
    labs(x= "DOC", y = "HIX")+
  scale_color_viridis_c()

chemjoin |> 
  left_join(waterlevel_precip, by = "Date") |> 
  ggplot(aes(x = DOC_mean, y = dam_depth_m, color = HIX_mean))+
  geom_point()


### BIX ~ DOC ###
chemjoin |> 
   # filter(Date < ymd("2024-12-01")) |> 
  ggplot(aes(x = DOC_mean, y = BIX_mean, color = as.factor(Date)))+
  geom_point() + #shape = 21,
  theme_bw()+ 
    labs(x= "DOC", y = "BIX")



### facet by site ###
chemjoin |> 
  ungroup() |> 
  dplyr::select(Site, Date, DOC_mean, HIX_mean) |> 
  pivot_longer(-c(1:2)) |> 
  ggplot(aes(x = Date, y = value, color = as.factor(Date)))+
  geom_point()+ theme(legend.position = "top")+
  facet_grid(name~factor(Site, levels = c(101,100,98,96,92,90,88,50)))


######### look at DOC at 98 and 96 in dec and feb; think cool under/overflow may be happening in FEB at P2
decfeb <- chemjoin |> 
  select(Site, Date, Depth_m, Site_Class, Distance, Dry_start, Dry_end, 
          DOC_mean, HIX_mean, SpCond_uScm) |> 
  rename(DOC_mgL = DOC_mean, HIX = HIX_mean) |> 
  filter(Date %in% c(ymd("2024-05-22"), ymd("2024-12-17"), ymd("2025-02-26"))) |> 
  filter(Distance < 400) |> #400 to keep C2; 700 to keep C3
  pivot_longer(-c(1:7)) |> 
  ggplot(aes(x = Distance, y = value, fill = Depth_m       ))+
  geom_rect(aes(xmin = Dry_start, xmax = Dry_end, ymin = -Inf, ymax = Inf), 
            alpha = 0.1, fill = "gray", color = NA )+ #color gets rid of border
  facet_grid(factor(name, levels = c("Temp_C", "SpCond_uScm", "DO_mgL", "DOC_mgL", "HIX"))~Date, scales = "free_y")+
  geom_point(shape = 21, size = 3)+
  theme_bw()+ 
  scale_fill_gradient2(low = "red",  high ="blue",
                       midpoint = 1,  guide = "colourbar")
  # scale_x_continuous(breaks = c(0, 500, 1000, 1500))
  # #scale_x_log10()+
  # scale_fill_gradient2(low = "red",  high ="blue",
  #                      midpoint = 6,  guide = "colourbar", breaks = c(3,6,9, 15, 20))

decfeb
# plotly::ggplotly(decfeb)

```

calc CV per Carla's comments 

```{r}

#### JUST CV 
data2 |> 
  group_by(Date) |> 
    summarise(DOCmean = mean(DOC_mean, na.rm = T),
              DOCsd = sd(DOC_mean, na.rm = T),
              HIXmean = mean(HIX_mean, na.rm = T),
              HIXsd = sd(HIX_mean, na.rm = T)
              ) |> 
  mutate(DOC_CV = (DOCsd/DOCmean)*100,
         HIX_CV = (HIXsd/HIXmean)*100) |> 
  select(Date, HIX_CV, DOC_CV) |> 
  pivot_longer(-1) |> 
  left_join(Dry_distance, by = "Date") |> 
  ggplot(aes(x = Date, y = value, color = name))+
  geom_line()+
  geom_point()



#### Add dry distance to plot 
Dry_distance <- data2 |> 
  filter(Site == 101,
         !is.na(HIX_mean)) |> 
  mutate(Dry_distance = Dry_end.x - Dry_start.x,
         Dry_distance = ifelse(is.na(Dry_distance), 0, Dry_distance)) |> 
  select(Date, Dry_distance)


# Define a scaling factor to align the two y-axes
scale_factor <- max(data2$DOC_CV, na.rm = TRUE) / max(Dry_distance$Dry_distance, na.rm = TRUE)

mdd <- max(Dry_distance$Dry_distance, na.rm = TRUE)

data2 |> 
  group_by(Date) |> 
    summarise(DOCmean = mean(DOC_mean, na.rm = TRUE),
              DOCsd = sd(DOC_mean, na.rm = TRUE),
              HIXmean = mean(HIX_mean, na.rm = TRUE),
              HIXsd = sd(HIX_mean, na.rm = TRUE)) |> 
  mutate(DOC_CV = (DOCsd / DOCmean) * 100,
         HIX_CV = (HIXsd / HIXmean) * 100) |> 
  select(Date, HIX_CV, DOC_CV) |> 
  pivot_longer(-1) |> 
  left_join(Dry_distance, by = "Date") |> 
  ggplot(aes(x = Date)) +
  # Primary y-axis plot
  geom_line(aes(y = value, color = name)) +
  geom_point(aes(y = value, color = name)) +
  # Secondary y-axis plot for Dry_distance
  geom_line(aes(y = (mdd - Dry_distance) * .5, linetype = "Dry Distance"), color = "black") +
  geom_point(aes(y = (mdd - Dry_distance) * .5, linetype = "Dry Distance"), color = "black") +
  scale_y_continuous(
    name = "HIX_CV and DOC_CV",
    sec.axis = sec_axis(~ mdd - (. / .5), name = "Dry Distance")
  ) +
  labs(color = "Variable", linetype = "") +
  theme_minimal()


```



IGC talk

```{r}

######## water level
igc_wl <- #CCR_usgs_data |> 
  waterlevel_precip |> rename(CCR_Dam_depth_m = dam_depth_m) |> 
  filter(Date > ymd("2024-04-15")) |> #filter(Date < ymd("2025-03-03")) |> 
  ggplot(aes(x = Date, y = CCR_Dam_depth_m))+  geom_point(size = 3)+
  geom_vline(xintercept = ymd("2024-05-22"), linetype = 2, linewidth = 1)+   geom_vline(xintercept = ymd("2024-06-19"), linetype = 2, linewidth = 1)+
  geom_vline(xintercept = ymd("2024-07-11"), linetype = 2, linewidth = 1)+    geom_vline(xintercept = ymd("2024-08-14"), linetype = 2, linewidth = 1)+ 
  geom_vline(xintercept = ymd("2024-09-16"), linetype = 2, linewidth = 1)+    geom_vline(xintercept = ymd("2024-09-30"), linetype = 2, linewidth = 1)+ 
  geom_vline(xintercept = ymd("2024-10-28"), linetype = 2, linewidth = 1)+   geom_vline(xintercept = ymd("2024-12-17"), linetype = 2, linewidth = 1)+  
  geom_vline(xintercept = ymd("2025-02-26"), linetype = 2, linewidth = 1)+  scale_x_date(breaks = "3 months", date_labels = "%b %Y")+
  labs(x= element_blank(), y = "Reservoir Water Level (m)")+  theme_bw()+ theme(text = element_text(size = 28),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())


  

#################### HIX and DOC

#HIX
igc_hix <- chemjoin |> 
   # filter(Date < ymd("2024-12-01")) |> 
  ggplot(aes(x = Distance, y = HIX_mean, fill = Depth_m))+
  geom_point(shape = 21, size = 4) + #shape = 21,
  geom_smooth()+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
    labs(x= "Distance from Stream (m)", y = "Humification Index (HIX)", fill = "Depth (m)",
       shape = "Site Type")+
  scale_x_continuous(breaks = c(0, 500, 1000, 1500))+ 
  scale_fill_gradient2(low = "red",  high ="blue",
                       midpoint = 6,  guide = "colourbar", breaks = c(3,6,9, 15))

#DOC
igc_doc <- chemjoin |> 
  #filter(Date < ymd("2024-12-01")) |> 
  ggplot(aes(x = Distance, y = DOC_mean, fill = Depth_m))+
  geom_point(shape = 21, size = 4) + #shape = 21,
  geom_smooth()+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
    labs(x= "Distance from Stream (m)", y = "DOC (mg/L)", fill = "Depth (m)",
       shape = "Site Type")+
  scale_x_continuous(breaks = c(0, 500, 1000, 1500))+ 
  scale_fill_gradient2(low = "red",  high ="blue",
                       midpoint = 6,  guide = "colourbar", breaks = c(3,6,9, 15))

igc_doc_hix <- ggpubr::ggarrange(igc_doc, igc_hix, nrow = 1, labels = "auto", font.label = list(size = 28))


 chemjoin |> 
  #filter(Date < ymd("2024-12-01")) |> 
  ggplot(aes(x = Distance, y = BIX_mean, fill = Depth_m))+
  geom_point(shape = 21, size = 4) + #shape = 21,
  geom_smooth()+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
    labs(x= "Distance from Stream (m)", y = "BIX", fill = "Depth (m)",
       shape = "Site Type")+
  scale_x_continuous(breaks = c(0, 500, 1000, 1500))+ 
  scale_fill_gradient2(low = "red",  high ="blue",
                       midpoint = 6,  guide = "colourbar", breaks = c(3,6,9, 15))



data2 |> 
  ggplot(aes(x = Distance, y = SpCond_uScm, fill = Depth_m))+
  geom_point(shape = 21, size = 4) + #shape = 21,
  geom_smooth()+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 28),
                    legend.text = element_text(size=18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
    labs(x= "Distance from Stream (m)", y = "Sp. Cond (uS/cm)",
       shape = "Site Type")+
  scale_x_continuous(breaks = c(0, 500, 1000, 1500))+ 
  scale_fill_gradient2(low = "red",  high ="blue",
                       midpoint = 6,  guide = "colourbar", breaks = c(3,6,9, 15))



################################### variables by date 

igc_dates <- data2 |> 
  #filter(Date %in% c(ymd("2024-05-22"), ymd("2024-08-14"), ymd("2024-09-16"), ymd("2024-09-30"), ymd("2024-10-28"))) |> 
  select(Site, Date, Depth_m, Site_Class, Distance, Dry_start, Dry_end, 
          #Temp_C, SpCond_uScm, DO_mgL, 
         DOC_mean, HIX_mean) |> 
  rename(DOC_mgL = DOC_mean, HIX = HIX_mean) |> 
  pivot_longer(-c(1:7)) |> 
  ggplot(aes(x = Distance, y = value, fill = Depth_m,
             #shape = factor(Site_Class, levels = c("Stream", "Pool", "Cove", "Pelagic"))
             ))+
  geom_rect(aes(xmin = Dry_start, xmax = Dry_end, ymin = -Inf, ymax = Inf), 
            alpha = 0.1, fill = "gray", color = NA )+ #color gets rid of border
  facet_grid(factor(name, levels = c("Temp_C", "SpCond_uScm", "DO_mgL", "DOC_mgL", "HIX"))~Date, scales = "free_y")+
  geom_point(shape = 21, size = 3)+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 14),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x= "Distance from Stream (m)", fill = "Depth (m)",
       shape = "Site Type")+
  scale_x_continuous(breaks = c(0, 500, 1000, 1500))+ #c(250, 750)
  # scale_shape_manual(values = c(24, 22, 21, 25))+ #18, 15, 16, 17
  scale_fill_gradient2(low = "red",  high ="blue",
                       midpoint = 6,  guide = "colourbar", breaks = c(3,6,9, 15))

igc_dates


### Multi EEMs
data2 |> 
  select(Site, Date, Depth_m, Site_Class, Distance, Dry_start, Dry_end, 
          BIX_mean, FI_mean, A_mean, T_mean, AT_mean, HIX_mean) |> 
  pivot_longer(-c(1:7)) |> 
  ggplot(aes(x = Distance, y = value, fill = Depth_m,
             #shape = factor(Site_Class, levels = c("Stream", "Pool", "Cove", "Pelagic"))
             ))+
  # geom_rect(aes(xmin = Dry_start, xmax = Dry_end, ymin = -Inf, ymax = Inf), alpha = 0.1, fill = "gray", color = NA )+ 
  # facet_grid(factor(name, levels = c("Temp_C", "SpCond_uScm", "DO_mgL", "DOC_mgL", "HIX"))~Date, scales = "free_y")+
    facet_wrap(~factor(name), scales = "free_y", nrow = 1)+
  geom_point(shape = 21, size = 3)+
  #geom_smooth()+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 14),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x= "Distance from Stream (m)", fill = "Depth (m)",
       shape = "Site Type")+
  scale_x_continuous(breaks = c(0, 500, 1000, 1500))+ #c(250, 750)
  scale_fill_gradient2(low = "red",  high ="blue",
                       midpoint = 6,  guide = "colourbar", breaks = c(3,6,9, 15))

  

```




## EEMs plots by distance, value on Y

Value on Y

```{r}

##### HIX 
#by date
eems_summary |> 
  ggplot(aes(x = Distance, y = HIX_mean, fill = Depth_m,
             shape = factor(Site_Class, levels = c("Stream", "Pool", "Cove", "Pelagic"))
             ))+
    geom_rect(aes(xmin = Dry_start, xmax = Dry_end, ymin = -Inf, ymax = Inf), 
            alpha = 0.1, fill = "gray", color = NA )+ #color gets rid of border
  geom_point( size = 3) + #shape = 21,
  geom_errorbar(aes(ymin = HIX_min, ymax = HIX_max), width = 2) +
  facet_wrap(~Date, scales = "fixed", ncol = 7)+ 
  # ylim(1.45,14.4)+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
    labs(x= "Distance from Stream (m)",
       shape = "Site Type")+
  scale_x_continuous(breaks = c(0, 500, 1000, 1500))+ 
  scale_shape_manual(values = c(24, 22, 21, 25))+ 
  scale_fill_gradient2(low = "red",  high ="blue",
                       midpoint = 6,  guide = "colourbar", breaks = c(3,6,9, 15, 20))


#across dates
eems_summary |> 
  ggplot(aes(x = Distance, y = HIX_mean, fill = Depth_m,
             ))+
  geom_point(shape = 21, size = 3) + #shape = 21,
  geom_smooth()+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
    labs(x= "Distance from Stream (m)",
       shape = "Site Type")+
  scale_x_continuous(breaks = c(0, 500, 1000, 1500))+ 
  scale_shape_manual(values = c(24, 22, 21, 25))+ 
  scale_fill_gradient2(low = "red",  high ="blue",
                       midpoint = 6,  guide = "colourbar", breaks = c(3,6,9, 15, 20))



##### BIX 
#by date
eems_summary |> 
  ggplot(aes(x = Distance, y = BIX_mean, fill = Depth_m,
             shape = factor(Site_Class, levels = c("Stream", "Pool", "Cove", "Pelagic"))
             ))+
    geom_rect(aes(xmin = Dry_start, xmax = Dry_end, ymin = -Inf, ymax = Inf), 
            alpha = 0.1, fill = "gray", color = NA )+ #color gets rid of border
  geom_point( size = 3) + #shape = 21,
  geom_errorbar(aes(ymin = BIX_min, ymax = BIX_max), width = 2) +
  facet_wrap(~Date, scales = "fixed", ncol = 7)+ 
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
    labs(x= "Distance from Stream (m)",
       shape = "Site Type")+
  scale_x_continuous(breaks = c(0, 500, 1000, 1500))+ 
  scale_shape_manual(values = c(24, 22, 21, 25))+ 
  scale_fill_gradient2(low = "red",  high ="blue",
                       midpoint = 6,  guide = "colourbar", breaks = c(3,6,9, 15, 20))


#across dates
eems_summary |> 
  ggplot(aes(x = Distance, y = BIX_mean, fill = Depth_m,
             ))+
  geom_point(shape = 21, size = 3) + #shape = 21,
  geom_smooth()+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
    labs(x= "Distance from Stream (m)",
       shape = "Site Type")+
  scale_x_continuous(breaks = c(0, 500, 1000, 1500))+ 
  scale_shape_manual(values = c(24, 22, 21, 25))+ 
  scale_fill_gradient2(low = "red",  high ="blue",
                       midpoint = 6,  guide = "colourbar", breaks = c(3,6,9, 15, 20))



```

Trying depth on Y 

```{r}

# maxdepth_df <- eems_summary |> 
#   group_by(Site, Date) |> 
#   summarise(max_depth = max(Depth_m) + 0.2)

summary(eems_summary$HIX_mean)

## trial 1 
eems_summary |> 
  group_by(Site, Date) |> 
  mutate(max_depth = max(Depth_m) + 0.5) |> 
  ggplot(aes(x = Distance, y = Depth_m , fill = HIX_mean))+
    geom_rect(aes(xmin = Dry_start, xmax = Dry_end, ymin = -Inf, ymax = Inf), 
            alpha = 0.1, fill = "gray", color = NA )+ #color gets rid of border
  geom_point(shape = 21, color = "black", size = 3) + 
   geom_line(aes(y = max_depth), color = "black")+
   geom_hline(yintercept = -0.5)+
  scale_y_reverse()+
  scale_y_continuous(trans = ggforce::trans_reverser('log10')) +
  facet_wrap(~Date, scales = "fixed", ncol = 7)+ 
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
    labs(x= "Distance from Stream (m)",
       shape = "Site Type")+
  scale_x_continuous(breaks = c(0, 500, 1000, 1500))+
    scale_fill_gradient(low = "green",  high ="brown",# midpoint = 5,
                         guide = "colourbar", breaks = c(1,3,5,7,9,11,13))



```


## EEMs change from site S1 

```{r}

eems_summary |> 
  select(1:7, HIX_mean) |> 
  pivot_wider(names_from = Site, values_from = HIX_mean)

s1 <- eems_summary |> 
  ungroup() |> 
  filter(Site == "101") |> 
  select(Site, Date, HIX_mean) |> 
  rename(HIX_S1 = HIX_mean)

#merged_df <- merge(eems_summary, s1[, c('Date', 'H')], by = c('Depth', 'Date'), suffixes = c("", "_SiteA"))

merged_df <- left_join(eems_summary, s1, by = "Date")

merged_df |> 
  mutate(diff_S1 = HIX_mean - HIX_S1) |> 
  ggplot(aes(x = Distance, y = diff_S1, fill = Depth_m,
             shape = factor(Site_Class, levels = c("Stream", "Pool", "Cove", "Pelagic"))
             ))+
  geom_rect(aes(xmin = Dry_start, xmax = Dry_end, ymin = -Inf, ymax = Inf), 
            alpha = 0.1, fill = "gray", color = NA )+ #color gets rid of border
  geom_point(size = 3) +  #shape = 21
  geom_hline(yintercept = 0)+
  facet_wrap(~Date, scales = "fixed", ncol = 7)+ 
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
    labs(x= "Distance from Stream (m)",
       shape = "Site Type")+
  scale_x_continuous(breaks = c(0, 500, 1000, 1500))+ 
  scale_shape_manual(values = c(24, 22, 21, 25))+ 
  scale_fill_gradient2(low = "red",  high ="blue",
                       midpoint = 6,  guide = "colourbar", breaks = c(3,6,9, 15, 20))


merged_df |> 
  mutate(diff_S1 = HIX_mean - HIX_S1) |> 
  ggplot(aes(x = Distance, y = diff_S1, fill = Depth_m,
             shape = factor(Site_Class, levels = c("Stream", "Pool", "Cove", "Pelagic"))
             ))+
  geom_point(size = 3) +  #shape = 21
  geom_hline(yintercept = 0)+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
    labs(x= "Distance from Stream (m)",
       shape = "Site Type")+
  scale_x_continuous(breaks = c(0, 500, 1000, 1500))+ 
  scale_shape_manual(values = c(24, 22, 21, 25))+ 
  scale_fill_gradient2(low = "red",  high ="blue",
                       midpoint = 6,  guide = "colourbar", breaks = c(3,6,9, 15, 20))
  


```



## MSN eems

```{r}
eems_MSN <- eems24 |> 
  mutate(Date = mdy(Date)) |> 
  filter(Date %in% c(ymd("2024-07-31"), ymd("2024-08-01")))

head(eems_MSN)

eems_MSN |> 
  ggplot(aes(x = factor(TIME, levels = c("noon", "midnight", "6am")), y = HIX., color = Depth_m))+
  geom_point()


eems_MSN |> 
  ggplot(aes(x = factor(TIME, levels = c("noon", "midnight", "6am")), y = BIX., color = Depth_m))+
  geom_point()

```




