---
title: "CCR spatial CTD and YSI measurements"
author: "Dexter Howard"
date: "2024-05-30"
output: html_document
---

## Read in packages 

```{r, include = F}
library(tidyverse)
# library(scales) #for date format on plots
# library(patchwork) #arrange figures w/ slashes and lines
# library(plotly)
# library(viridis)

```


## Temp/Cond across sites

Get YSI data 

```{r}
## YSI data
# ysi_gsheet <- gsheet::gsheet2tbl("https://docs.google.com/spreadsheets/d/1HbSBEFjMuK4Lxit5MRbATeiyljVAB-cpUNxO3dKd8V8/edit#gid=1787819257")

ysi_L1 <- read.csv("https://raw.githubusercontent.com/CareyLabVT/Reservoirs/master/Data/DataNotYetUploadedToEDI/YSI_PAR/ysi_L1.csv")

ccr_ysi <- ysi_L1 |>
  filter(Reservoir == "CCR") |>
  mutate(Date = as.Date(DateTime)) |>
  filter(year(Date) > 2023)

```


CTD cleaning function 

```{r}
###function to clean ctd casts
ccr_ctd_clean <- function(data){

  #slice by depth for each reservoir
    depths = seq(0.1, 23, by = 1)
    df.final<-data.frame()

 for (i in 1:length(depths)){
      
      fp_layer <- data %>% 
        mutate(Date = as.Date(DateTime)) |> 
        group_by(Date, Site) |>  
        slice(which.min(abs(as.numeric(Depth_m) - depths[i])))
      
      # Bind each of the data layers together.
      df.final = bind_rows(df.final, fp_layer)%>%
      mutate(Depth_m = round(Depth_m, digits = 1)) |> 
       dplyr::distinct() 
 }
    return(df.final)
}

```


Get CTD Data

```{r}
### read in raw data 
ctd_L1 <- read_csv("https://raw.githubusercontent.com/CareyLabVT/Reservoirs/master/Data/DataNotYetUploadedToEDI/Raw_CTD/ctd_L1.csv")

ccr_ctd_24 <- ctd_L1 |> 
  mutate(Date = as.Date(DateTime)) |> 
  select(Reservoir, Site, Date, everything()) |> 
  filter(Reservoir == "CCR")

ccr_ctd_24 <- ccr_ctd_clean(ccr_ctd_24)


```


CTD check plots 

```{r}
#plot 4 focal variables and remove known bad points

ccr_ctd_24 |> 
  filter(Chla_ugL < 50) |> #remove crazy high chla at site 90 (likely sensor in mud)
  mutate(SpCond_uScm = ifelse(Date == ymd("2024-06-19") & SpCond_uScm < 110, NA, SpCond_uScm )) |> #remove Cond bubble issues that should get worked out at some point
  pivot_longer(-c(1:6)) |> 
  filter(name %in% c("Temp_C", "SpCond_uScm", "DO_mgL", "Chla_ugL", "CDOM_ugL")) |> 
  # filter(Site == 50) |> 
  ggplot(aes(x = value, y = Depth_m, color = as.factor(Date)))+
  geom_line(orientation = "y")+
  scale_y_reverse()+
  facet_grid(Site~name, scales = "free")+
  theme_bw()

```

## Bring CTD to YSI

```{r}
##bind data togheter
# head(ctd_22may24)
# head(ccr_ysi)

ctd_bind <- ccr_ctd_24 |> 
  select(Reservoir, Site, Date, Depth_m, Temp_C, DO_mgL, DOsat_percent, SpCond_uScm)

ysi_bind <- ccr_ysi |> 
  select(Reservoir, Site, Date, Depth_m, Temp_C, DO_mgL, DOsat_percent, SpCond_uScm) |> 
  filter(!Site %in% c(88,90))

sensors <- rbind(ctd_bind, ysi_bind) |> 
  mutate(Distance_ft = ifelse(Site == 101, 0, NA),
         Distance_ft = ifelse(Site == 100, 407, Distance_ft),
         Distance_ft = ifelse(Site == 98, 619, Distance_ft),
         Distance_ft = ifelse(Site == 96, 790, Distance_ft),
         Distance_ft = ifelse(Site == 94, 1015, Distance_ft),
         Distance_ft = ifelse(Site == 92, 1132, Distance_ft),
         Distance_ft = ifelse(Site == 90, 1843, Distance_ft),
         Distance_ft = ifelse(Site == 88, 3326, Distance_ft),
         Distance_ft = ifelse(Site == 50, 5011, Distance_ft)
         ) |> 
  mutate(Site_code = ifelse(Site == 101, "S1", NA),
         Site_code = ifelse(Site == 100, "S2", Site_code),
         Site_code = ifelse(Site == 98, "P1", Site_code),
         Site_code = ifelse(Site == 96, "P2", Site_code),
         Site_code = ifelse(Site == 94, "C1", Site_code),
         Site_code = ifelse(Site == 92, "C2", Site_code),
         Site_code = ifelse(Site == 90, "C3", Site_code),
         Site_code = ifelse(Site == 88, "C4", Site_code),
         Site_code = ifelse(Site == 50, "50", Site_code)
         ) |> 
  select(Reservoir, Site, Site_code, Date, Depth_m, Distance_ft, everything())


```


## Dot plots - old style

```{r}

##previous style plot
levels_sites <- c(101, 100, 98, 96, 94, 92, 90, 88, 50)
levels_sites_code <- c("S1", "S2", "P1", "P2", "C1", "C2", "C3", "C4", "50")

sensors |> 
  select(-DO_mgL) |> 
  pivot_longer(-c(1:6)) |> 
  mutate(Depth_m = ifelse(Depth_m == 1.1, 1, Depth_m),
         Depth_m = ifelse(Depth_m == 0.4, 0.5, Depth_m)) |> #just to make color gradient a lil cleaner
  #filter(Site > 50) |> #trim site 50 to help w/ viz
  #ggplot(aes(x = factor(Site, level = levels_sites), y = value, color = as.factor(Depth_m)))+
  ggplot(aes(x = factor(Site_code, levels = levels_sites_code), y = value, color = as.factor(Depth_m)))+
  geom_point(size = 3)+
  #facet_wrap(~name, nrow = 3, scales = "free_y")+
  facet_grid(name~Date, scales = "free_y")+
  # labs(title = "HPB", y = "Temp (C)", x = "Site")+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 18))+
  guides(color = guide_legend(nrow=2, byrow=TRUE))
  #scale_color_gradient("Depth_m",  high = "red", low = "blue") 
  


```



## Heatmaps 

```{r}

fp_new <- sensors |> 
  filter(Date == ymd("2024-05-22")) |> 
  mutate(Distance = Distance_ft*0.3048) |> 
   filter(Site < 100)

#Temp
  interp_temp <- akima::interp(x=as.numeric(fp_new$Distance), y = fp_new$Depth_m, z = fp_new$Temp_C,
                   xo = seq(min(fp_new$Distance), max(fp_new$Distance), by = 10),
                   yo = seq(min(fp_new$Depth_m), max(fp_new$Depth_m), by = 0.1),
                   extrap = T, linear = T, duplicate = "strip")
  interp_temp <- akima::interp2xyz(interp_temp, data.frame=T)

ggplot(interp_temp, aes(x=x, y=y))+
    geom_raster(aes(fill=z))+
    scale_y_reverse(expand = c(0,0))+
    scale_x_continuous(expand = c(0, 0)) +
    geom_point(data = fp_new, aes(x = (Distance_ft*0.3048), y = 0.1, z = NULL), pch = 25, size = 3, fill = "black")+ #to mark cast sites 
    scale_fill_gradientn(colours = colorRamps::blue2green2red(60), na.value="gray")+
    labs(x = "Distance from Stream (m)", y = "Depth (m)", title = "Temp CCR 22may24")+
    theme_bw()
  
  
#Cond
#   interp_spcond <- akima::interp(x=as.numeric(fp_new$Distance), y = fp_new$Depth_m, z = fp_new$SpCond_uScm,
#                    xo = seq(min(fp_new$Distance), max(fp_new$Distance), by = 10),
#                    yo = seq(min(fp_new$Depth_m), max(fp_new$Depth_m), by = 0.5),
#                    extrap = T, linear = T, duplicate = "strip")
#   interp_spcond <- akima::interp2xyz(interp_spcond, data.frame=T)
#   
#   # max_depths <- fp_new |> 
#   #   group_by(Site, Distance) |> 
#   #   summarise(max_depth = max(Depth_m))
#   
#   # interp_spcond_v2 <- interp_spcond |> 
#   #   mutate(x_2 = ifelse(x < ))
#   
# ggplot(interp_spcond, aes(x=x, y=y))+
#     geom_raster(aes(fill=z))+
#     scale_y_reverse(expand = c(0,0))+
#     scale_x_continuous(expand = c(0, 0)) +
#     # geom_point(data = sensor_22may24, aes(x = (Distance_ft*0.3048), y = 0.1, z = NULL), pch = 25, size = 3, fill = "black")+ #to mark cast sites ; (sensor_22may24 |> filter(!Site ==50))
#     scale_fill_gradientn(colours = colorRamps::blue2green2red(60), na.value="gray")+
#     labs(x = "Distance from Stream (m)", y = "Depth (m)", title = "Sp.Cond CCR 22may24")+
#     theme_bw()
# 
# fp_new
# ggplot(fp_new, aes(x = Distance, y = Depth_m)) +
#   geom_contour_filled(aes(z = Temp_C), bins = 5) +
#   scale_fill_brewer(palette = "Spectral") +
#   labs(x = "distance", y = "Depth (m)", fill = "Temperature (°C)") +
#   theme_minimal() + 
#   scale_y_reverse()


```


## Cove HOBO buoys 

get data together from April - July 11
```{r}
hobo_P1_top <- read.csv("https://raw.githubusercontent.com/CareyLabVT/ManualDownloadsSCCData/master/CCR_manual_downloads/CCR_Hobos/Cove_Pool_buoys/hobo101_P1_top_11jul24.csv", skip = 1) |> 
  select(2:3) |> rename(DateTime = 1, Temp_C = 2) |> mutate(Site = "P1", Depth = "TOP")

hobo_P1_mid <- read.csv("https://raw.githubusercontent.com/CareyLabVT/ManualDownloadsSCCData/master/CCR_manual_downloads/CCR_Hobos/Cove_Pool_buoys/hobo51_P1_mid_11jul24.csv", skip = 1) |> 
    select(2:3) |> rename(DateTime = 1, Temp_C = 2) |> mutate(Site = "P1", Depth = "MID")


hobo_P1_bot <- read.csv("https://raw.githubusercontent.com/CareyLabVT/ManualDownloadsSCCData/master/CCR_manual_downloads/CCR_Hobos/Cove_Pool_buoys/hobo36_P1_bot_11jul24.csv", skip = 1) |> 
    select(2:3) |> rename(DateTime = 1, Temp_C = 2) |> mutate(Site = "P1", Depth = "BOT")


hobos_P1 <- rbind(hobo_P1_top, hobo_P1_mid, hobo_P1_bot) |> 
  mutate(DateTime = mdy_hms(DateTime))


```

plot data
```{r}
#plot raw data
hobos_P1 |> 
  ggplot(aes(x = DateTime, y = Temp_C, color = Depth))+
  geom_line()+
  geom_vline(xintercept = ymd_hms("2024-05-22 00:00:00"))+
  geom_vline(xintercept = ymd_hms("2024-06-19 00:00:00"))+
  geom_vline(xintercept = ymd_hms("2024-07-11 00:00:00"))+
  # facet_wrap(~Depth)+
  theme_classic()

hobos_P1 |> 
  filter(DateTime >= ymd("2024-06-01")) |> 
  ggplot(aes(x = DateTime, y = Temp_C, color = Depth))+
  geom_line()+
  geom_vline(xintercept = ymd_hms("2024-05-22 00:00:00"))+
  geom_vline(xintercept = ymd_hms("2024-06-19 00:00:00"))+
  geom_vline(xintercept = ymd_hms("2024-07-11 00:00:00"))+
  # facet_wrap(~Depth)+
  theme_classic()

#plot daily data
hobos_P1 |> 
  mutate(Date = as.Date(DateTime)) |> 
  group_by(Date, Depth) |> 
  summarize(Temp_C = mean(Temp_C, na.rm = T)) |> 
  ggplot(aes(x = Date, y = Temp_C, color = Depth))+
  geom_line()+
  geom_vline(xintercept = ymd_hms("2024-05-22 00:00:00"))+
  geom_vline(xintercept = ymd_hms("2024-06-19 00:00:00"))+
  geom_vline(xintercept = ymd_hms("2024-07-11 00:00:00"))+
  # facet_wrap(~Depth)+
  theme_classic()


```














