---
title: "Breakpoints"
output: html_document
date: "2025-07-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Packages
```{r}
library(ggpubr) # for ggdensity
library(segmented)
library(tidyverse)
```

## Set up data

site characteristics

```{r}

Site_code_number <- data.frame(Site_code = c("CS1", "CS2", "CP1", "CP2", "CC1", "CC2", "CC3", "CC4", "C50"),
                               Site_number = c(101, 100, 98, 96, 94, 92, 90, 88, 50))

## bring in distances and site class table from google sheets; have to redownload locally each time 
distances <- read.csv("C:/Users/dwh18/Downloads/2024 spatial sampling - Distances (2).csv") |> 
  mutate(Date = mdy(Date)) |> 
  dplyr::select(-c(13,14)) |> 
  pivot_longer(-c(1,11,12), names_to = "Site_code", values_to = "Distance_ft") |> 
  filter(!Site_code == "C1") 


site_class <- read.csv("C:/Users/dwh18/Downloads/2024 spatial sampling - Sites_Class (2).csv") |> 
  dplyr::select(-X, -Key) |> 
  mutate(Date = mdy(Date)) |> 
  pivot_longer(-c(1), names_to = "Site_code", values_to = "Site_Class") |> 
  mutate(Site_Class = ifelse(Site_Class %in% c("S", "S "), "Stream", Site_Class),
         Site_Class = ifelse(Site_Class %in% c("P", "P "), "Pool", Site_Class),
         Site_Class = ifelse(Site_Class == "C", "Cove", Site_Class),
         Site_Class = ifelse(Site_Class == "L", "Pelagic", Site_Class))

```

read in EEMS
```{r}
eems24 <- read.csv("../EEMs_Results_2024.csv")

eems <- eems24 |> 
    mutate(Date = mdy(Date),
           Date = ifelse(Date == ymd("2024-08-15"), ymd("2024-08-14"), Date),
           Date = ifelse(Date == ymd("2025-02-17"), ymd("2025-02-26"), Date),
           Date = as.Date(Date),
         Site_code = ifelse(Site == 101, "S1", NA),
         Site_code = ifelse(Site == 100, "S2", Site_code),
         Site_code = ifelse(Site == 98, "P1", Site_code),
         Site_code = ifelse(Site == 96, "P2", Site_code),
         Site_code = ifelse(Site == 94, "C1", Site_code),
         Site_code = ifelse(Site == 92, "C2", Site_code),
         Site_code = ifelse(Site == 90, "C3", Site_code),
         Site_code = ifelse(Site == 88, "C4", Site_code),
         Site_code = ifelse(Site == 50, "C50", Site_code)
         ) |> 
  dplyr::select(Reservoir, Site, Site_code, Depth_m, Date, FI., HIX., BIX., T., A., A.T., a254, a350, A254, A350, NOTES)


eems_plotting <- left_join(eems, distances, by = c("Site_code", "Date")) |> 
  left_join(site_class, by = c("Site_code", "Date")) |> 
  mutate(Distance = Distance_ft*0.3048,
         Dry_start = Dry_start*0.3048,
         Dry_end = Dry_end*0.3048) |> 
  filter(!Date %in% c(ymd("2024-07-31"), ymd("2024-08-01"))) |> 
  dplyr::select(Reservoir, Site, Site_code, Site_Class, Depth_m, Date, Distance, Dry_start, Dry_end, FI., HIX., BIX., T., A., A.T., a254, a350, NOTES)


eems_plotting

eems_summary <- eems_plotting |> 
  filter(!NOTES %in% c("PART", "FRIDGE_TEST")) |> 
  filter(Site_code != "C1") |> 
  rename(HIX = HIX.,
         BIX = BIX.,
         FI = FI.,
         A = A.,
         peakT = T.,
         AT = A.T.) |>  #### can just change the rename here for what value you want to look at
  dplyr::select(Site, Site_Class, Depth_m, Date, Distance, Dry_start, Dry_end, HIX, BIX, FI, A, peakT, AT) |> 
  group_by(Site, Site_Class, Depth_m, Date, Dry_start, Dry_end, Distance) |> 
  summarise(HIX_mean = mean(HIX, na.rm = T),
            HIX_min = min(HIX, na.rm = T),
            HIX_max = max(HIX, na.rm = T),
            BIX_mean = mean(BIX, na.rm = T),
            BIX_min = min(BIX, na.rm = T),
            BIX_max = max(BIX, na.rm = T),
            FI_mean = mean(FI, na.rm = T),
            A_mean = mean(A, na.rm = T),
            T_mean = mean(peakT, na.rm = T),
            AT_mean = mean(AT, na.rm = T)
            ) |> 
  mutate(Rep = ifelse(HIX_mean != HIX_min, "Y", "N"))



```



read in DOC
```{r}

# ccr_solubles <- read_csv("C:/Users/dwh18/OneDrive/Desktop/Alab_QAQC/EDI2025/Solubles_DOC_joined_v2.csv") |>
#   filter(Reservoir == "CCR") |> 
#   mutate(Date = mdy(Date),
#          Site_code = ifelse(Site == 101, "S1", NA),
#          Site_code = ifelse(Site == 100, "S2", Site_code),
#          Site_code = ifelse(Site == 98, "P1", Site_code),
#          Site_code = ifelse(Site == 96, "P2", Site_code),
#          Site_code = ifelse(Site == 94, "C1", Site_code),
#          Site_code = ifelse(Site == 92, "C2", Site_code),
#          Site_code = ifelse(Site == 90, "C3", Site_code),
#          Site_code = ifelse(Site == 88, "C4", Site_code),
#          Site_code = ifelse(Site == 50, "C50", Site_code))

```





join datasets

```{r}
#set up data
chem <- full_join(eems_summary, solubles_summary, by = c("Site", "Date", "Depth_m")) |> 
  full_join(iso_plotting, by = c("Site", "Date", "Depth_m")) |> 
  mutate(Site_Class = ifelse(Site_Class == "Pool", "Backwater", Site_Class)) |> 
  mutate(Site_Type_static = ifelse(Site %in% c(50,88), "Pelagic", NA),
         Site_Type_static = ifelse(Site %in% c(90,92), "Cove", Site_Type_static),
         Site_Type_static = ifelse(Site %in% c(96,98), "Backwater", Site_Type_static),
         Site_Type_static = ifelse(Site %in% c(100,101), "Stream", Site_Type_static)
  ) 

```


## Normality test

```{r}
#### normality
  ##https://www.sthda.com/english/wiki/normality-test-in-r

ggdensity(chem$BIX_mean, xlab = "BIX", main = "Density plot of BIX in CCR")
shapiro.test(chem$BIX_mean) # p-values < 0.05 means data is not normally distributed
ggdensity(chem$DOC_mean, xlab = "DOC (mg/L)", main = "Density plot of DOC in CCR")
shapiro.test(chem$DOC_mean) 
ggdensity(chem$d2H_VSMOW, xlab = "dH2", main = "Density plot of dH2 in CCR")
shapiro.test(chem$d2H_VSMOW) 

```


## Make nice plots of each variable

```{r}
## make nice plots

#DOC
doc_clean <- chem |> 
  ggplot(aes(x = Distance, y = DOC_mean, fill = Depth_m))+
  geom_point(shape = 21, size = 4) + #shape = 21,
  # geom_smooth()+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x= "Distance from Stream (m)", y = "DOC (mg/L)", fill = "Depth (m)",
       shape = "Site Type")+
  scale_x_continuous(breaks = c(0, 500, 1000, 1500))+ 
  scale_fill_gradient2(low = "red",  high ="blue",
                       midpoint = 6,  guide = "colourbar", breaks = c(3,6,9, 15))

doc_clean

#BIX
bix_clean <- chem |> 
  ggplot(aes(x = Distance, y = BIX_mean, fill = Depth_m))+
  geom_point(shape = 21, size = 4) + #shape = 21,
  # geom_smooth()+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x= "Distance from Stream (m)", y = "BIX", fill = "Depth (m)",
       shape = "Site Type")+
  scale_x_continuous(breaks = c(0, 500, 1000, 1500))+ 
  scale_fill_gradient2(low = "red",  high ="blue",
                       midpoint = 6,  guide = "colourbar", breaks = c(3,6,9, 15))

bix_clean

#BIX
hix_clean <- chem |> 
  ggplot(aes(x = Distance, y = HIX_mean, fill = Depth_m))+
  geom_point(shape = 21, size = 4) + #shape = 21,
  # geom_smooth()+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x= "Distance from Stream (m)", y = "HIX", fill = "Depth (m)",
       shape = "Site Type")+
  scale_x_continuous(breaks = c(0, 500, 1000, 1500))+ 
  scale_fill_gradient2(low = "red",  high ="blue",
                       midpoint = 6,  guide = "colourbar", breaks = c(3,6,9, 15))

hix_clean

#d2H
d2H_clean <- chem |> 
  ggplot(aes(x = Distance, y = d2H_VSMOW, fill = Depth_m))+
  geom_point(shape = 21, size = 4) + #shape = 21,
  # geom_smooth()+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x= "Distance from Stream (m)", y = "d2H (VSMOW)", fill = "Depth (m)",
       shape = "Site Type")+
  scale_x_continuous(breaks = c(0, 500, 1000, 1500))+ 
  scale_fill_gradient2(low = "red",  high ="blue",
                       midpoint = 6,  guide = "colourbar", breaks = c(3,6,9, 15))

d2H_clean


```


## Make boxplots across sites for each variable 

how many samples are different site types depending on grouping
```{r}
#changing sites
chem |>   group_by(Site_Class) |> 
  summarise(Count = n()) 

#fixed
chem |>   group_by(Site_Type_static) |> 
  summarise(Count = n()) 

```


BIX boxplots
```{r}
#### By Site Type (Static)

#kruskal and dunn test
kruskal <- kruskal.test(BIX_mean ~ Site_Type_static, data = chem)
kruskal
dunn <- FSA::dunnTest(BIX_mean ~ Site_Type_static, data = chem)
dunn_letters <- dunn$res
dunn_letters_list <- rcompanion::cldList(comparison = dunn_letters$Comparison, p.value = dunn_letters$P.adj, threshold = 0.05)

level_order <- c("Stream", "Backwater", "Cove", "Pelagic")
 
bix_boxplot_type <- left_join(chem, dunn_letters_list, by = c("Site_Type_static" = "Group")) %>%
  ggplot(aes(x = factor(Site_Type_static, level = level_order), y = BIX_mean))+   
  geom_boxplot(outlier.alpha = 0)+ #, outlier.alpha = 0
  #geom_violin()+
  geom_jitter(width = 0.2)+
  stat_compare_means(method = "kruskal.test", label.y = 0.94, label.x = 1.3, size = 4)+ 
  geom_text(aes(x = Site_Type_static, label = Letter), y = 0.92, size = 5)+
  theme_bw()+ theme(text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x = "Site Type (Static)", y = "BIX")

bix_boxplot_type





#### By Site Class (Changes)

#kruskal and dunn test
kruskal <- kruskal.test(BIX_mean ~ Site_Class, data = chem)
kruskal
dunn <- FSA::dunnTest(BIX_mean ~ Site_Class, data = chem)
dunn_letters <- dunn$res
dunn_letters_list <- rcompanion::cldList(comparison = dunn_letters$Comparison, p.value = dunn_letters$P.adj, threshold = 0.05)

level_order <- c("Stream", "Backwater", "Cove", "Pelagic")
 
left_join(chem, dunn_letters_list, by = c("Site_Class" = "Group")) %>%
  ggplot(aes(x = factor(Site_Class, level = level_order), y = BIX_mean))+   
  geom_boxplot(outlier.alpha = 0)+ #, outlier.alpha = 0
  #geom_violin()+
  geom_jitter(width = 0.2)+
  stat_compare_means(method = "kruskal.test", label.y = 0.94, label.x = 1.3, size = 4)+ 
  geom_text(aes(x = Site_Class, label = Letter), y = 0.92, size = 5)+
  theme_bw()+ theme(text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x = "Site Class (Changes)", y = "BIX")

```

HIX boxplots
```{r}
#### By Site Type (Static)

#kruskal and dunn test
kruskal <- kruskal.test(HIX_mean ~ Site_Type_static, data = chem)
kruskal
dunn <- FSA::dunnTest(HIX_mean ~ Site_Type_static, data = chem)
dunn_letters <- dunn$res
dunn_letters_list <- rcompanion::cldList(comparison = dunn_letters$Comparison, p.value = dunn_letters$P.adj, threshold = 0.05)

level_order <- c("Stream", "Backwater", "Cove", "Pelagic")
 
hix_boxplot_type <- left_join(chem, dunn_letters_list, by = c("Site_Type_static" = "Group")) %>%
  ggplot(aes(x = factor(Site_Type_static, level = level_order), y = HIX_mean))+   
  geom_boxplot(outlier.alpha = 0)+ #, outlier.alpha = 0
  #geom_violin()+
  geom_jitter(width = 0.2)+
  stat_compare_means(method = "kruskal.test", label.y = 13.3, label.x = 1.3, size = 4)+ 
  geom_text(aes(x = Site_Type_static, label = Letter), y = 13, size = 5)+
  theme_bw()+ theme(text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x = "Site Type (Static)", y = "HIX")

hix_boxplot_type


```

DOC boxplots
```{r}
#### By Site Type (Static)

#kruskal and dunn test
kruskal <- kruskal.test(DOC_mean ~ Site_Type_static, data = chem)
kruskal
dunn <- FSA::dunnTest(DOC_mean ~ Site_Type_static, data = chem)
dunn_letters <- dunn$res
dunn_letters_list <- rcompanion::cldList(comparison = dunn_letters$Comparison, p.value = dunn_letters$P.adj, threshold = 0.05)

level_order <- c("Stream", "Backwater", "Cove", "Pelagic")
 
doc_boxplot_type <- left_join(chem, dunn_letters_list, by = c("Site_Type_static" = "Group")) %>%
  ggplot(aes(x = factor(Site_Type_static, level = level_order), y = DOC_mean))+   
  geom_boxplot(outlier.alpha = 0)+ #, outlier.alpha = 0
  #geom_violin()+
  geom_jitter(width = 0.2)+
  stat_compare_means(method = "kruskal.test", label.y = 5, label.x = 1.3, size = 4)+ 
  geom_text(aes(x = Site_Type_static, label = Letter), y = 4.8, size = 5)+
  theme_bw()+ theme(text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x = "Site Type (Static)", y = "DOC (mg/L)")

doc_boxplot_type


```

d2H boxplots
```{r}
#### By Site Type (Static)

#kruskal and dunn test
kruskal <- kruskal.test(d2H_VSMOW ~ Site_Type_static, data = chem)
kruskal
dunn <- FSA::dunnTest(d2H_VSMOW ~ Site_Type_static, data = chem)
dunn_letters <- dunn$res
dunn_letters_list <- rcompanion::cldList(comparison = dunn_letters$Comparison, p.value = dunn_letters$P.adj, threshold = 0.05)

level_order <- c("Stream", "Backwater", "Cove", "Pelagic")
 
d2H_boxplot_type <- left_join(chem, dunn_letters_list, by = c("Site_Type_static" = "Group")) %>%
  ggplot(aes(x = factor(Site_Type_static, level = level_order), y = d2H_VSMOW))+   
  geom_boxplot(outlier.alpha = 0)+ #, outlier.alpha = 0
  #geom_violin()+
  geom_jitter(width = 0.2)+
  stat_compare_means(method = "kruskal.test", label.y = -22, label.x = 1.3, size = 4)+ 
  geom_text(aes(x = Site_Type_static, label = Letter), y = -23, size = 5)+
  theme_bw()+ theme(text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x = "Site Type (Static)", y = "d2H (% VSMOW)")

d2H_boxplot_type


```


## Breakpoints 

BIX
```{r}
#fit normal linear regression 
my.lm <- lm(BIX_mean ~ Distance, data = chem)
summary(my.lm)

#Run breakpoint
my.seg <- segmented(my.lm,  seg.Z = ~ Distance,  psi = 2 )
summary(my.seg)
my.seg$psi
slope(my.seg)

#fit breakpoint segments to distance data
my.fitted <- fitted(my.seg)
my.model <- data.frame(Distance = chem$Distance, BIX_fit = my.fitted)

#get breakpoint lines
my.lines <- my.seg$psi[ , 2]

#plot
bix_breakpoint <- bix_clean+
  #geom_smooth()+
  geom_vline(xintercept = my.lines, linetype = "dashed", size = 1.5) +
  geom_line(data = my.model, aes(x = Distance, y = BIX_fit), size = 1, inherit.aes = FALSE ) 

bix_breakpoint

```


HIX
```{r}
#fit normal linear regression 
my.lm <- lm(HIX_mean ~ Distance, data = chem)
summary(my.lm)

#Run breakpoint
my.seg <- segmented(my.lm,  seg.Z = ~ Distance,  psi = 2 )
summary(my.seg)
my.seg$psi
slope(my.seg)

#fit breakpoint segments to distance data
my.fitted <- fitted(my.seg)
my.model <- data.frame(Distance = chem$Distance, HIX_fit = my.fitted)

#get breakpoint lines
my.lines <- my.seg$psi[ , 2]

#plot
hix_breakpoint <- hix_clean+
  #geom_smooth()+
  geom_vline(xintercept = my.lines, linetype = "dashed", size = 1.5) +
  geom_line(data = my.model, aes(x = Distance, y = HIX_fit), size = 1, inherit.aes = FALSE ) 

hix_breakpoint

```

DOC
```{r}
#fit normal linear regression 
my.lm <- lm(DOC_mean ~ Distance, data = chem)
summary(my.lm)

#Run breakpoint
my.seg <- segmented(my.lm,  seg.Z = ~ Distance,  psi = 2 )
summary(my.seg)
my.seg$psi
slope(my.seg)

#fit breakpoint segments to distance data
my.fitted <- fitted(my.seg)
my.model <- data.frame(Distance = chem$Distance, DOC_fit = my.fitted)

#get breakpoint lines
my.lines <- my.seg$psi[ , 2]

#plot
doc_breakpoint <- doc_clean+
  #geom_smooth()+
  geom_vline(xintercept = my.lines, linetype = "dashed", size = 1.5) +
  geom_line(data = my.model, aes(x = Distance, y = DOC_fit), size = 1, inherit.aes = FALSE ) 

doc_breakpoint

```


d2H
```{r}
#fit normal linear regression 
my.lm <- lm(d2H_VSMOW ~ Distance, data = chem)
summary(my.lm)

#Run breakpoint
my.seg <- segmented(my.lm,  seg.Z = ~ Distance,  psi = 2 )
summary(my.seg)
my.seg$psi
slope(my.seg)

#fit breakpoint segments to distance data
my.fitted <- fitted(my.seg)
my.model <- data.frame(Distance = chem$Distance, d2H_fit = my.fitted)

#get breakpoint lines
my.lines <- my.seg$psi[ , 2]

#plot
d2H_breakpoint <- d2H_clean+
  #geom_smooth()+
  geom_vline(xintercept = my.lines, linetype = "dashed", size = 1.5) +
  geom_line(data = my.model, aes(x = Distance, y = d2H_fit), size = 1, inherit.aes = FALSE ) 

d2H_breakpoint

```

## Put figures together

```{r}
library(patchwork) # | is for side by side

(doc_breakpoint | bix_breakpoint | hix_breakpoint | d2H_breakpoint  ) / 
 (doc_boxplot_type | bix_boxplot_type | hix_boxplot_type | d2H_boxplot_type)
            

##agu abstract
doc_breakpoint | hix_breakpoint



```





