---
title: "CCR_hydrology_2024"
author: "Dexter Howard"
date: "2024-06-20"
output: html_document
---

## packages 
```{r}
library(tidyverse)
library(ggpmisc) #stat poly line
library(plotly)
```


## HOBO water level calculations

```{r}
########### get data ###############

### CCR dam for water level
ccr_dam_edi <- read_csv("https://pasta.lternet.edu/package/data/eml/edi/1069/3/4afb209b30ebed898334badd3819d854" )
ccr_dam_git <- read_csv("https://raw.githubusercontent.com/FLARE-forecast/CCRE-data/refs/heads/ccre-dam-data-qaqc/ccre-waterquality_L1.csv") 

ccr_dam <- rbind(ccr_dam_edi, ccr_dam_git)

waterlevel_10min <- ccr_dam |> filter(DateTime > ymd("2024-04-01")) |> ggplot(aes(x = DateTime, y = LvlDepth_m_13))+geom_point()

waterlevel_10min

ccr_dam |> 
  mutate(Date = as.Date(DateTime)) |> 
  group_by(Date) |> 
  summarise(#pressure = mean(LvlPressure_psi_13, na.rm = T),
            dam_depth_m = mean(LvlDepth_m_13, na.rm = T)) |> 
  mutate(Year = year(Date), Month = month(Date), Day = day(Date),
         FakeDate = ymd(paste(2032, Month, Day, sep = "-"))) |> 
  filter(dam_depth_m > 15) |> 
  ggplot(aes(x = FakeDate, y = dam_depth_m, color = as.factor(Year)))+
    geom_line(linewidth = 2) + scale_x_date(date_labels = "%b") + theme_bw()

### CCR met 
ccr_met_edi <- read_csv("https://pasta.lternet.edu/package/data/eml/edi/1105/3/df0ce4fc90f220b65c400b997abae37b")
ccr_met_git <- read_csv("https://raw.githubusercontent.com/FLARE-forecast/CCRE-data/refs/heads/ccre-dam-data-qaqc/ccre_met_L1.csv") 

ccr_met <- ccr_met_edi |> 
  select(-starts_with("Note")) |> #remove note columns to bind
  rbind(ccr_met_git) 

##format for bind 
ccr_met_bind <- ccr_met |> 
  select(DateTime, BP_Average_kPa, Flag_BP_Average_kPa) |> 
  mutate(Date = as.Date(DateTime),
         Hour = hour(DateTime),
         Min = minute(DateTime)) |> 
  filter(Min %in% c(0,10,20,30,40,50)) |>  #get just minutes to line up w/ HOBO
  rename(DateTime_EST = DateTime) |> 
  select(DateTime_EST, BP_Average_kPa, Flag_BP_Average_kPa) 
#check BP flag
  

### HOBO water level
hpb_hobo_16sep24 <- read_csv("https://raw.githubusercontent.com/CareyLabVT/ManualDownloadsSCCData/master/CCR_manual_downloads/CCR_Hobos/HPB_waterlevel/hobo_hpb_16sep24.csv", skip = 1) |> 
  select(2:4)

hpb_hobo_17dec24 <- read_csv("https://raw.githubusercontent.com/CareyLabVT/ManualDownloadsSCCData/master/CCR_manual_downloads/CCR_Hobos/HPB_waterlevel/hobo_hpb_17dec24_2.csv", skip = 1) |> 
  select(2:4)

hpb_hobo <- rbind(hpb_hobo_16sep24, hpb_hobo_17dec24)

#set time where sensor may have been out of the water
maintenance <- c(seq(ymd_hms("2024-05-22 15:00:00"), ymd_hms("2024-05-22 16:00:00"), by = "10 min"),
                 seq(ymd_hms("2024-06-19 11:00:00"), ymd_hms("2024-06-19 12:20:00"), by = "10 min"),
                 seq(ymd_hms("2024-07-11 11:00:00"), ymd_hms("2024-07-11 12:00:00"), by = "10 min"),
                 seq(ymd_hms("2024-09-16 13:00:00"), ymd_hms("2024-09-16 14:00:00"), by = "10 min"),
                 seq(ymd_hms("2024-09-30 12:30:00"), ymd_hms("2024-09-30 14:00:00"), by = "10 min"),
                 seq(ymd_hms("2024-10-28 13:00:00"), ymd_hms("2024-10-28 14:00:00"), by = "10 min"),
                 seq(ymd_hms("2024-12-17 13:30:00"), ymd_hms("2024-12-17 14:00:00"), by = "10 min")
                 )

hobo_bind <- hpb_hobo |> 
  rename(DateTime_EDT = 1, 
         HOBO_Abs_Pres_kPa = 2,
         Temp_C = 3) |> 
  #select(DateTime_EDT, HOBO_Abs_Pres_kPa, Temp_C) |> 
  mutate(DateTime_EDT = mdy_hms(DateTime_EDT)) |> 
  filter(!DateTime_EDT %in% maintenance) |> 
  mutate(Date = as.Date(DateTime_EDT),
         Hour = hour(DateTime_EDT),
         Min = minute(DateTime_EDT)) |> 
  mutate(Time_EST = paste(Hour+1, Min, 00, sep = ":"),
         DateTime_EST = ymd_hms(paste(Date, Time_EST, sep = " "))  ) |> 
  select(DateTime_EST, HOBO_Abs_Pres_kPa, Temp_C) 





############## bind data and calculate water level #######################

waterlevel_correct <- left_join(hobo_bind, ccr_met_bind, by = "DateTime_EST") |> 
  select(-Flag_BP_Average_kPa) |> 
  mutate(corrected_Pres_kPa = HOBO_Abs_Pres_kPa - BP_Average_kPa) |> 
  mutate(waterlevel_cm = corrected_Pres_kPa * 10.1972)

#stream temp hysteresis
waterlevel_correct |> 
  ggplot(aes(x = waterlevel_cm, y = Temp_C, color = DateTime_EST))+
  geom_point()+
  theme_bw() + labs(title = "10 min data")


waterlevel_correct |> 
  mutate(Date = as.Date(DateTime_EST)) |> 
  group_by(Date) |> 
  summarise(stage = mean(waterlevel_cm, na.rm = T),
            temp = mean(Temp_C, na.rm = T)) |> 
  ggplot(aes(x = stage, y = temp, color = Date))+
  geom_point()+
  theme_bw() + labs(title = "Daily")

############### plot 10-min data ######################

waterlevel_correct |> 
  ggplot()+
  geom_line(aes(x=DateTime_EST, y = BP_Average_kPa, color = "MET"))+  
  geom_line(aes(x=DateTime_EST, y = HOBO_Abs_Pres_kPa, color = "HOBO_raw"))+
  geom_line(aes(x=DateTime_EST, y = corrected_Pres_kPa + 95, color = "HOBO_correct + 95"))

waterlevel_correct |> 
  ggplot(aes(x = DateTime_EST, y = waterlevel_cm))+
  geom_line()

############## compile daily data for well, dam, rain ######################

##precip plot 
daily_rain <- ccr_met |> 
  filter(DateTime > ymd("2024-04-01")) |> 
  mutate(Date = as.Date(DateTime)) |> 
  group_by(Date) |> 
  summarise(Daily_rain_mm = sum(Rain_Total_mm, na.rm = T))

 rainplot <- daily_rain|> 
  ggplot(aes(x = Date, y = Daily_rain_mm))+
  geom_point()+
  geom_line()
 
 rainplot
 
 ##Dam water level plot
 daily_dam_waterlevel <- ccr_dam |> 
  mutate(Date = as.Date(DateTime)) |> 
  group_by(Date) |> 
  summarise(#pressure = mean(LvlPressure_psi_13, na.rm = T),
            dam_depth_m = mean(LvlDepth_m_13, na.rm = T)) 
  
#get daily water level and precip
waterlevel_daily <- waterlevel_correct |> 
  mutate(Date = as.Date(DateTime_EST)) |> 
  group_by(Date) |> 
  summarise(HPB_Daily_waterlevel_cm = mean(waterlevel_cm, na.rm = T))

waterlevel_precip <-  left_join(daily_rain, waterlevel_daily, by = "Date")
waterlevel_precip <-  left_join(waterlevel_precip, daily_dam_waterlevel, by = "Date")



```

##Compare to USGS data 

Set up data

```{r}
library(dataRetrieval)

#get data from USGS
sitenos <- c("02055100" , "02018500")

#get site info
siteinfo <- readNWISsite(sitenos)
data_available <- whatNWISdata(siteNumber = sitenos, service = "dv") #can remove dv to get other variables

#get daily Q
startDate <- "2024-04-01" # "1987-01-01"
#startDate <- "2020-01-01"
endDate <- Sys.Date()
parameter <- "00060" # 00060 is daily Q; 00065 is stage 
stage <- "00065"

Qdat <- readNWISdv(sitenos, parameter, startDate, endDate) %>% 
  renameNWISColumns()

Qdata <- left_join(Qdat, siteinfo, by = c("site_no"))

stage_dat <- readNWISuv(sitenos, stage, startDate, endDate) %>% 
  renameNWISColumns()

stagedata <- left_join(stage_dat, siteinfo, by = c("site_no"))

stagedata |> 
  ggplot(aes(x = dateTime, y = GH_Inst, col = site_no))+
  geom_point()+
  labs(title = "USGS gauges height: 15 min")

## check out long term patterns in USGS sites
# Qdata |> 
#   ggplot(aes(x = Date, y = Flow, color = station_nm))+
#   geom_point()+
#   scale_y_log10()+
#   theme_bw()+
#   theme(legend.position = "top")

#################### subset data to compare to HPB ####################################

Qdata |> 
  filter(Date >= ymd("2024-04-15")) |> 
  ggplot(aes(x = Date, y = Flow, color = site_no))+
  geom_line()

Qdata_forjoin <- Qdata |> 
  select(Date, site_no, Flow) |> 
  pivot_wider(names_from = site_no, values_from = Flow, names_prefix = "Flow_")

stagedata_forjoin <- stagedata |> 
  mutate(Date = as.Date(dateTime)) |> 
  group_by(Date, site_no) |> 
  summarise(Stage = mean(GH_Inst, na.rm = T)) |> 
  pivot_wider(names_from = site_no, values_from = Stage, names_prefix = "Stage_")

# Join data together for 4 variable plot
CCR_usgs_data <- left_join(Qdata_forjoin, waterlevel_precip, by= "Date") |> 
  left_join(stagedata_forjoin, by = "Date") |> 
  rename(CCR_Dam_depth_m = dam_depth_m,
         CCR_MetStation_daily_rain_mm = Daily_rain_mm,
         CCR_HPB_daily_waterlevel_cm = HPB_Daily_waterlevel_cm,
         USGS_CatwabaCreek_dailyflow_cfs = Flow_02018500,
         USGS_TinkerCreek_dailyflow_cfs = Flow_02055100,
         USGS_CatwabaCreek_dailystage_ft = Stage_02018500,
         USGS_TinkerCreek_dailystage_ft = Stage_02055100) |> 
  filter(Date > ymd("2024-04-15")) 

```


Plots 

```{r}

faceted_hydro <- CCR_usgs_data |> 
  #filter(Date > ymd("2024-08-01")) |> 
  select(-USGS_CatwabaCreek_dailyflow_cfs) |> 
  select(-USGS_CatwabaCreek_dailystage_ft) |> 
  select(-USGS_TinkerCreek_dailyflow_cfs) |> 
  # select(-USGS_TinkerCreek_dailystage_ft) |> 
  pivot_longer(-1) |> 
  ggplot(aes(x = Date, y = value))+
  geom_point()+
  #scale_y_log10()+
  geom_vline(xintercept = ymd("2024-05-22"))+  geom_vline(xintercept = ymd("2024-06-19"))+
  geom_vline(xintercept = ymd("2024-07-11"))+  geom_vline(xintercept = ymd("2024-08-14"))+
  geom_vline(xintercept = ymd("2024-09-16"))+  geom_vline(xintercept = ymd("2024-09-30"))+
  geom_vline(xintercept = ymd("2024-10-28"))+  geom_vline(xintercept = ymd("2024-12-17"))+
  geom_vline(xintercept = ymd("2025-02-26"))+
  facet_wrap(~factor(name, levels = c("CCR_MetStation_daily_rain_mm", "CCR_HPB_daily_waterlevel_cm", "USGS_TinkerCreek_dailyflow_cfs", "USGS_TinkerCreek_dailystage_ft", "CCR_Dam_depth_m")), ncol = 1, scales = "free_y")+
  scale_x_date(breaks = "1 months", date_labels = "%b")+
  labs(x= element_blank())+
  theme_bw()+ theme(text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())

faceted_hydro
#plotly::ggplotly(faceted_hydro)

```


USGS regressions

```{r}

###USGS to HPB regression

#Tinker
CCR_usgs_data |> 
  ggplot(aes(x = USGS_TinkerCreek_dailyflow_cfs, y = CCR_HPB_daily_waterlevel_cm))+
  geom_point()+
  stat_poly_line(method = "lm", linewidth = 2)+
  stat_poly_eq(formula=y~x, label.x = "left", label.y="top", parse=TRUE, inherit.aes = F,
               aes(x = USGS_TinkerCreek_dailyflow_cfs, y = CCR_HPB_daily_waterlevel_cm, label=paste(..adj.rr.label..,..p.value.label..,sep="~~~"),size=3))+
  theme_bw()

CCR_usgs_data |> 
  ggplot(aes(x = USGS_TinkerCreek_dailystage_ft, y = CCR_HPB_daily_waterlevel_cm))+
  geom_point()+
  stat_poly_line(method = "lm", linewidth = 2)+
  stat_poly_eq(formula=y~x, label.x = "left", label.y="top", parse=TRUE, inherit.aes = F,
               aes(x = USGS_TinkerCreek_dailystage_ft, y = CCR_HPB_daily_waterlevel_cm, label=paste(..adj.rr.label..,..p.value.label..,sep="~~~"),size=3))+
  theme_bw()


# #### logistic fits
# test <- CCR_usgs_data |> 
#   rename(hpb = CCR_HPB_daily_waterlevel_cm, usgs = USGS_CatwabaCreek_dailystage_ft) |> 
#   filter(hpb > 0, 
#          !is.na(hpb)) |> 
#   mutate(hpb = hpb/30.48)
# 
# # logistic_model <- glm(hpb ~ usgs, data = test, family = poisson)
# # 
# # broom::tidy(logistic_model)
# 
# logistic_model <- nls(hpb ~ a / (1 + exp(-(usgs - b) / c)), data = test,
#                       start = list(a = median(test$hpb), b = median(test$usgs), c = 1))
# 
# model_summary <- summary(logistic_model)
# model_summary
# 
# ggplot(test, aes(x = usgs, y = hpb)) +
#   geom_point() +
#   stat_function(fun = function(x) coef(logistic_model)[1] /
#                               (1 + exp(-(x - coef(logistic_model)[2]) / coef(logistic_model)[3])),
#                 color = "blue") +
#   labs(title = "Logistic Curve Fit", x = "USGS", y = "HPB")



#### GAMS 
library(mgcv)

test <- CCR_usgs_data |> 
  rename(hpb = CCR_HPB_daily_waterlevel_cm, catawba = USGS_CatwabaCreek_dailystage_ft,
         tinker = USGS_TinkerCreek_dailystage_ft) |> 
  mutate(catawba = catawba*30.48,
         tinker = tinker*30.48)

test |> 
  ggplot(aes(x = catawba, y = hpb))+
  geom_point()+
  geom_smooth(method = "gam", formula = y ~ s(x))

##catawba gam 
model <- gam(hpb ~ s(catawba), data = test) 
summary(model)

test$predicted_hpb_C <- predict(model, newdata = test)

#tinker gam
model2 <- gam(hpb ~ s(tinker), data = test) 
summary(model2)

test$predicted_hpb_T <- predict(model2, newdata = test)

#both gam
model3 <- gam(hpb ~ s(catawba) + s(tinker), data = test) 
summary(model3)

test$predicted_hpb_CT <- predict(model3, newdata = test)

#plot
gamsplot <- test |> 
  #select(Date, catawba, tinker, hpb, predicted_hpb_C, predicted_hpb_T, predicted_hpb_CT) |> 
  select(Date, hpb, predicted_hpb_C, predicted_hpb_T, predicted_hpb_CT) |> 
  pivot_longer(-1) |> 
ggplot(aes(x= Date, y= value, color = name)) +
  geom_line() +
  #scale_y_log10()+
  theme_bw()

ggplotly(gamsplot)

```


## Get flowmate Q

```{r}
raw_q <- gsheet::gsheet2tbl("https://docs.google.com/spreadsheets/d/1fgYcGsZeALuwdAX3H0UeA3u57zKsuqTkouh2bxuBTKw/edit?gid=0#gid=0")

#format data and calculate Q
ccr_flowmate <- raw_q |> 
  mutate(Date = mdy(Date)) |> 
  filter(Reservoir == "CCR", 
         Site == 101) |> 
    filter(Method %in% c("Flowmate", "Flowmeter")) %>%   #filter to just flowmate measurements 
  mutate(Depth_m = Depth_cm/100,    
         Velocity_m.s = ifelse(Velocity_unit %in% c("ft_s", "ft/s"), Velocity*0.3048, Velocity), 
         Discharge = Depth_m * Velocity_m.s * WidthInterval_m    ) %>% 
  group_by(Reservoir, Site, Date) %>% #group by site and date
  summarise(Discharge_m3s = sum(Discharge, na.rm = T),  #sum across intervals to get final discharge
         Method = "F") |> 
  mutate(L_s = Discharge_m3s * 1000) |> 
  left_join(waterlevel_precip, by = "Date") |> 
  mutate(month = month(Date)) 

#plot of flowmate data 
ccr_flowmate |> ggplot(aes(x = Date, y = L_s))+ 
  geom_point()+ geom_line()

  
#fit model 
exp.model <-lm(L_s ~ exp(HPB_Daily_waterlevel_cm), ccr_flowmate)

#plot linear model fit
ccr_flowmate |> 
  ggplot(aes(x = HPB_Daily_waterlevel_cm, y = L_s, color = month)) +
  geom_point() +
  stat_poly_line(method = "lm", linewidth = 2)+
  stat_poly_eq(formula=y~x, label.x = "left", label.y="top", parse=TRUE, inherit.aes = F,
               aes(x = HPB_Daily_waterlevel_cm, y = L_s, label=paste(..adj.rr.label..,..p.value.label..,sep="~~~"),size=3))+
    # geom_smooth(method="lm", formula= (y ~ exp(x)), se=FALSE, linetype = 1) +
  labs(x = "HPB water level (cm)", y = "Flowmate (m3s)")+
  theme_bw()
  

# #log fit trial
# ccr_flowmate |> 
#   ggplot(aes(x = HPB_Daily_waterlevel_cm, y = L_s, color = month)) +
#   geom_point() +
#   geom_smooth(method="nls", se=FALSE, formula=L_s~a*log(HPB_Daily_waterlevel_cm)+k,
#               method.args=list(start=c(a=0, k=1)))

#exponential fit from stackoverflow; https://stackoverflow.com/questions/73816347/how-to-fit-exponential-model-in-r-and-print-correct-y-abx-equation
eq_fmt <- "`y`~`=`~%.3g~italic(e)^{%.3g~`x`}"

ccr_flowmate |> 
  ggplot(aes(x = HPB_Daily_waterlevel_cm, y = L_s, color = month)) +
  geom_point(size = 3) + 
  stat_smooth(method = "lm", formula =  y ~ exp(x))+
  stat_poly_eq(mapping = aes(x = HPB_Daily_waterlevel_cm, y = L_s,
                             label = sprintf(eq_fmt, 
                                             after_stat(b_0), 
                                             after_stat(b_1))), 
               label.x = 0.1, label.y = 0.85,
               formula =  y ~ exp(x), 
               output.type = "numeric",
               parse = TRUE
  ) +
  stat_poly_eq(label.x=0.1, label.y=0.8, 
               aes(x = HPB_Daily_waterlevel_cm, y = L_s,label = paste(..rr.label..)), formula =  y ~ exp(x),
               parse = TRUE, size = 3.5)+
  theme_classic()
  
```

Format data for WVWA 

```{r}

# daily_waterlevel_flowmate <- left_join(waterlevel_precip, ccr_flowmate, by = "Date") |> 
#   select(Date, Daily_rain_mm, dam_depth_m, HPB_Daily_waterlevel_cm, L_s) |> 
#   rename(Manual_discharge_L_s = L_s) |> 
#   filter(Date >= ymd("2024-04-23"),
#          Date <= ymd("2024-12-17"))
# 
# write.csv(daily_waterlevel_flowmate, "C:/Users/dwh18/Downloads/CCR_daily_waterlevel.csv", row.names = F)
# 
# lm(Manual_discharge_L_s~HPB_Daily_waterlevel_cm, data = daily_waterlevel_flowmate)
# 
# 
# hf_hpb_wl <- waterlevel_correct |> 
#   select(DateTime_EST, Temp_C, waterlevel_cm)
# 
# write.csv(hf_hpb_wl, "C:/Users/dwh18/Downloads/CCR_stream_hf_waterlevel.csv", row.names = F)



```



S1 hysterisis 

```{r}
## EEMS
eems24 <- read.csv("../EEMs_Results_2024.csv")

S1_eems <- eems24 |> 
  mutate(Date = mdy(Date)) |> 
  mutate(Date = ifelse(Date == ymd("2024-08-15"), ymd("2024-08-14"), Date)) |>
  mutate(Date = as.Date(Date)) |> 
  filter(Site == 101) |> 
  group_by(Date) |> 
  summarise(HIX = mean(HIX., na.rm = T),
            BIX = mean(BIX., na.rm = T))


left_join(S1_eems, ccr_flowmate, by = "Date") |> 
  ggplot(aes(y = HIX, x = L_s))+
  geom_point(aes(color = as.factor(Date)), size = 5)+
  geom_path()+
  theme_bw()+ theme(legend.position = "right", text = element_text(size = 18))+
  labs(y = "HIX", x = "Q (L/s)", color = "Date")


##Solubles 
ccr_solubles1 <- read.csv("./solubles1_v2.csv")
ccr_solubles2 <- read.csv("./solubles2_v2.csv") |> 
  rename(NH4 = 14, PO4 = 15, NO3 = 16)

ccr_solubles <- rbind(ccr_solubles1, ccr_solubles2) |> 
  mutate(NO3 = ifelse(NO3 < 0, 0, NO3),
         NH4 = ifelse(NH4 < 0, 0, NH4),
         PO4 = ifelse(PO4 < 0, 0, PO4)) |> 
  mutate(Date = mdy(Date)) |> 
  mutate(Site_code = ifelse(Date == ymd("2024-05-22") & Site_code == "CC4", "CC3", Site_code),
         Site_code = ifelse(Date == ymd("2024-05-22") & Site_code == "CC5", "CC4", Site_code)) |> 
  mutate(Site_code = substr(Site_code, 2, nchar(Site_code))) |> 
  mutate(Site_code = ifelse(Site_code =="50", "C50", Site_code)) |> 
  mutate(Date = ifelse(Date == ymd("2024-08-15"), ymd("2024-08-14"), Date),
         Date = as.Date(Date)) |> 
  rename(DOC = 10)

S1_solubles <- ccr_solubles |> 
  filter(Site_number == 101) |> 
  group_by(Date) |> 
  summarise(DOC = mean(DOC, na.rm = T), NO3 = mean(NO3, na.rm = T), PO4 = mean(PO4, na.rm = T), NH4 = mean(NH4, na.rm = T)) |> 
  left_join(S1_eems, by = "Date") |> 
  pivot_longer(-1)

left_join(S1_solubles, ccr_flowmate, by = "Date") |> 
  ggplot(aes(y = value, x = L_s))+  
  geom_point(aes(color = as.factor(Date)), size = 5)+
  facet_wrap(~name, scales = "free_y")+
  geom_path()+  theme_bw()+ theme(legend.position = "right", text = element_text(size = 18))+
  labs(y = "value", x = "Q (L/s)", color = "Date")
  

```





