---
title: "Untitled"
output: html_document
date: "2025-11-24"
---

#### First read in all data till you get the 'chem' df from Breakpoints


## get hydrology data

```{r}
#read in data
hydro_data <- read.csv("./Hydro_dailyData.csv") |> 
  mutate(Date = ymd(Date)) |> 
  #clunky filter to fix period with messed up presure transducer
  mutate(CCR_Dam_depth_m = ifelse(Date >= ymd("2025-03-13") & Date <= ymd("2025-04-03"), CCR_Dam_depth_m + 0.4, CCR_Dam_depth_m)) |>
  filter(CCR_Dam_depth_m < 20)


##plot daily dam water level
agu_hydro <- hydro_data |> 
  filter(Date > ymd("2024-04-15")) |> 
  filter(Date < ymd("2025-05-01")) |> 
  ggplot(aes(x = Date, y = CCR_Dam_depth_m))+  geom_point(size = 3)+
  geom_vline(xintercept = ymd("2024-05-22"), linetype = 2, linewidth = 1)+   
  geom_vline(xintercept = ymd("2024-06-19"), linetype = 2, linewidth = 1)+
  geom_vline(xintercept = ymd("2024-07-11"), linetype = 2, linewidth = 1)+    
  geom_vline(xintercept = ymd("2024-08-14"), linetype = 2, linewidth = 1)+ 
  geom_vline(xintercept = ymd("2024-09-16"), linetype = 2, linewidth = 1)+    
  geom_vline(xintercept = ymd("2024-09-30"), linetype = 2, linewidth = 1)+ 
  geom_vline(xintercept = ymd("2024-10-28"), linetype = 2, linewidth = 1)+   
  geom_vline(xintercept = ymd("2024-12-17"), linetype = 2, linewidth = 1)+  
  geom_vline(xintercept = ymd("2025-02-26"), linetype = 2, linewidth = 1)+  
  geom_vline(xintercept = ymd("2025-04-16"), linetype = 2, linewidth = 1)+  
  scale_x_date(breaks = "2 months", date_labels = "%b %y")+
  labs(x= element_blank(), y = "Reservoir Depth (m)")+  
  theme_bw()+ theme(text = element_text(size = 24), # axis.text.x = element_text(angle = 10, hjust = 1),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())

# plotly::ggplotly(agu_hydro)
agu_hydro

ggsave("AGU25_figs/Dam_WL.png", agu_hydro, width = 9.5, height = 5.5, units = "in")

```


#### Isotope plots 

```{r}

##d2H and d18O and D excess
chem |> 
    dplyr::select(1:10, d18O_VSMOW, d2H_VSMOW, D_excess) |> 
  pivot_longer(-c(1:10)) |> 
  ggplot(aes(x = Distance, y = value, fill = Depth_m
  ))+
  geom_point(shape = 21, size = 3) + 
  #geom_point(data = iso_rain, mapping = aes(x = 1250, y = value, color = Date), size = 2, shape = 17)+
  facet_wrap(~name, scales = "free_y", nrow = 2)+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x= "Distance from Stream (m)",  fill = "Depth (m)", color = "Rain")+
  scale_x_continuous(breaks = c(0, 500, 1000, 1500))+  
  scale_fill_gradient2(low = "red",  high ="blue",
                       midpoint = 6,  guide = "colourbar", breaks = c(3,6,9, 15, 20))


```

D excess timeseries 

```{r}

## D excess sites by depth 

#set up levels factors

iso_levels_sites <- c("S1", "S2", "B1", "B2", "C1", "C2", "P1", "P2")

iso_levels <- c("S1_0.1", "S2_0.1", "B1_0.1", "B1_BOT", "B2_0.1", "B2_BOT", "C1_0.1", "C1_BOT",
                "C2_0.1", "C2_1.5", "C2_BOT",
                "P1_0.1", "P1_1.5", "P1_6", "P1_9", "P1_BOT",
                "P2_0.1", "P2_1.5", "P2_6", "P2_9", "P2_BOT")

iso_levels2 <- c("S1_0.1", "S2_0.1", "B1_0.1",  "B2_0.1",  "C1_0.1",  "C2_0.1", "P1_0.1", "P2_0.1",
                 "C2_1.5", "P1_1.5", "P2_1.5", "B1_BOT",  "B2_BOT", "C1_BOT", "C2_BOT",
                  "P1_6", "P1_9", "P1_BOT","P2_6", "P2_9", "P2_BOT")


iso_plotting <- chem |> 
  dplyr::select(1:10, d18O_VSMOW, d2H_VSMOW, D_excess) |> 
  #set up naming to make sites by depth and sitee
  dplyr::mutate(Depth_new = as.character(ifelse(Site %in% c(98,96,92) & Depth_m > 0.1, "BOT", Depth_m)),
         Depth_new = as.character(ifelse(Site == 90 & Depth_m > 1.5, "BOT", Depth_new)),
         Depth_new = as.character(ifelse(Site %in% c(88,50) & Depth_m > 9, "BOT", Depth_new))
         ) |> 
  mutate(Site_code_new = ifelse(Site == 101, "S1", NA),
         Site_code_new = ifelse(Site == 100, "S2", Site_code_new),
         Site_code_new = ifelse(Site == 98, "B1", Site_code_new),
         Site_code_new = ifelse(Site == 96, "B2", Site_code_new),
         Site_code_new = ifelse(Site == 92, "C1", Site_code_new),
         Site_code_new = ifelse(Site == 90, "C2", Site_code_new),
         Site_code_new = ifelse(Site == 88, "P1", Site_code_new),
         Site_code_new = ifelse(Site == 50, "P2", Site_code_new),
  ) |> 
  mutate(Site_CODE = paste(Site_code_new, Depth_new, sep = "_"))


## D excess Top and Bottom plot
iso_plotting |> 
  filter(Depth_new %in% c("0.1", "BOT")) |> 
  # filter(Site %in% c(101,100,98,96)) |> 
  mutate(TOP_BOT = ifelse(Depth_new %in% c("0.1"), "TOP", "BOT")) |> 
  ggplot(aes(x =Date, y = D_excess, 
             color = factor(Site_code_new, levels = iso_levels_sites),
             linetype = factor(TOP_BOT, levels = c("TOP", "BOT"))
             ))+
  geom_point(size = 3) +  geom_line(size = 1.3)+
  labs(x = "Date", y = "Deuterium excess", color = "Site_Depth", linetype = "Depth")+
  annotate("text", x = ymd("2024-06-01"), y = 18,
           label = "D excess = dD - 8*d18O", size = 5, color = "black", hjust = 0)+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  guides(color = guide_legend(nrow = 2, byrow = TRUE))+ # Arrange legend in 2 rows, filling by row
  scale_color_viridis_d(option = "H") #a-h are color options

## D excess Top only plot
iso_plotting |> 
  filter(Depth_new %in% c("0.1")) |> 
  ggplot(aes(x =Date, y = D_excess, 
             color = factor(Site_code_new, levels = iso_levels_sites)))+
  geom_point(size = 3) +  geom_line(size = 1.3)+
  labs(x = "Date", y = "Deuterium excess", color = "Site_Depth", linetype = "Depth")+
  annotate("text", x = ymd("2024-06-01"), y = 18,
           label = "D excess = dD - 8*d18O", size = 5, color = "black", hjust = 0)+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  guides(color = guide_legend(nrow = 2, byrow = TRUE))+ # Arrange legend in 2 rows, filling by row
  scale_color_viridis_d(option = "H") #a-h are color options


```


Change color scheme and points so each site type has same color 

```{r}
#to see virdis color codes
#viridis_pal(option = "H")(8)
iso_levels_sites <- c("S1", "S2", "B1", "B2", "C1", "C2", "P1", "P2")


site_colors <- c("S1" = "#30123BFF", "S2" = "#30123BFF",
                 "B1" = "#1BD0D5FF", "B2" = "#1BD0D5FF",
                 "C1" = "#D2E935FF", "C2" = "#D2E935FF",
                 "P1" = "#DB3A07FF", "P2" = "#DB3A07FF")

site_shapes <- c("S1" = 15, "S2" = 16,
                 "B1" = 15, "B2" = 16,
                 "C1" = 15, "C2" = 16,
                 "P1" = 15, "P2" = 16)

iso_plotting %>%
  mutate(Site_group = substr(Site_code_new, 1, 1),   # S, B, C, P
         Number     = substr(Site_code_new, 2, 2),   # 1 or 2
         Legend_key = Site_code_new) %>%             # combined key
  filter(Depth_new %in% c("0.1")) %>%
  ggplot(aes(x = Date, y = D_excess,
             color = Legend_key,
             shape = Legend_key,
             group = Legend_key)) +
  geom_point(size = 3) +
  geom_line(size = 1.3) +
  labs(x = "Date", y = "Deuterium excess", color = "Site", shape = "Site") +
  annotate("text", x = ymd("2024-06-01"), y = 18,
           label = "D excess = dD - 8*d18O", size = 5, color = "black", hjust = 0) +
  theme_bw() +
  theme(
    legend.position = "top",
    text = element_text(size = 18),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  ) +
  guides(color = guide_legend(nrow = 2, byrow = TRUE)) +
  scale_x_date(date_labels = "%b %Y ")+
  scale_color_manual(values = site_colors, breaks = iso_levels_sites) +
  scale_shape_manual(values = site_shapes, breaks = iso_levels_sites)


```

Add rain now 

```{r}

iso_levels_sites <- c("S1","S2","B1","B2","C1","C2","P1","P2")

site_colors <- c("S1" = "#30123BFF", "S2" = "#30123BFF",
                 "B1" = "#1BD0D5FF", "B2" = "#1BD0D5FF",
                 "C1" = "#D2E935FF", "C2" = "#D2E935FF",
                 "P1" = "#DB3A07FF", "P2" = "#DB3A07FF")

site_shapes <- c("S1" = 15, "S2" = 16,
                 "B1" = 15, "B2" = 16,
                 "C1" = 15, "C2" = 16,
                 "P1" = 15, "P2" = 16)

# Build plotting dataset with rain
plot_data <- iso_plotting %>%
  filter(Depth_new %in% c("0.1")) %>%
  full_join(hydro_data, by = "Date") %>%
  rename(Rain_mm = CCR_MetStation_daily_rain_mm) %>%
  filter(Date >= ymd("2024-05-01"),
         Date <= ymd("2025-05-01")) %>%
  mutate(Legend_key = Site_code_new)

# Scaling factor for rainfall bars
max_dexcess <- max(plot_data$D_excess, na.rm = TRUE)
max_rain    <- max(plot_data$Rain_mm, na.rm = TRUE)
scale_factor <- max_dexcess / max_rain

ggplot() +
  # Rain bars (no legend)
  geom_col(data = plot_data,
           aes(x = Date, y = Rain_mm * scale_factor),
           fill = "lightblue", width = 1,
           show.legend = FALSE) +

  # Isotope points and lines
  geom_point(data = plot_data,
             aes(x = Date, y = D_excess,
                 color = Legend_key,
                 shape = Legend_key,
                 group = Legend_key),
             size = 3) +
  geom_line(data = plot_data,
            aes(x = Date, y = D_excess,
                color = Legend_key,
                group = Legend_key),
            size = 1.3) +

  # Labels and annotation
  labs(x = "Date", y = "Deuterium excess", color = "Site", shape = "Site") +
  # annotate("text", x = ymd("2024-06-01"), y = 18,
  #          label = "D excess = dD - 8*d18O",
  #          size = 5, color = "black", hjust = 0) +

  # Theme
  theme_bw() +
  theme(
    legend.position = "top",
    text = element_text(size = 18),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  ) +
  guides(color = guide_legend(nrow = 2, byrow = TRUE)) +

  # Manual scales with enforced order
    scale_x_date(date_labels = "%b %Y ")+
  scale_color_manual(values = site_colors, breaks = iso_levels_sites) +
  scale_shape_manual(values = site_shapes, breaks = iso_levels_sites) +

  # Secondary axis for rainfall
  scale_y_continuous(
    sec.axis = sec_axis(~ . / scale_factor, name = "Rainfall (mm)")
  )

# ggsave("AGU25_figs/iso2_SBCP_rain.png", width = 9.5, height = 5.5, units = "in")


```



#for AGU plots to make one group at a time

```{r}

iso_plotting |> 
  filter(Depth_new %in% c("0.1")) |> 
  # filter(Site_code_new %in% c("S1", "S2", "B1", "B2", "C1", "C2", "P1", "P2")) |> 
    filter(Site_code_new %in% c("S1", "S2")) |> 
  mutate(Site_group = substr(Site_code_new, 1, 1),   # S, B, C, P
         Number     = substr(Site_code_new, 2, 2),   # 1 or 2
         Legend_key = Site_code_new) %>%             # combined key
  ggplot(aes(x = Date, y = D_excess,
             color = Legend_key,
             shape = Legend_key,
             group = Legend_key)) +
  geom_point(size = 3) +
  geom_line(size = 1.3) +
  labs(x = "Date", y = "Deuterium excess", color = "Site", shape = "Site") +
  # annotate("text", x = ymd("2024-06-01"), y = 18,
  #          label = "D excess = dD - 8*d18O", size = 5, color = "black", hjust = 0) +
  theme_bw() +
  theme(
    legend.position = "top",
    text = element_text(size = 18),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  ) +
  guides(color = guide_legend(nrow = 2, byrow = TRUE)) +
  scale_x_date(date_labels = "%b %Y ")+
  ylim(0,19)  +
  scale_color_manual(values = site_colors, breaks = iso_levels_sites) +
  scale_shape_manual(values = site_shapes, breaks = iso_levels_sites)


# ggsave("AGU25_figs/iso2_S.png", width = 9, height = 5.5, units = "in")



```


## Iso TS with bot or all depths plotted

```{r}

iso_levels_sites <- c("S1","S2","B1","B2","C1","C2","P1","P2")

site_colors <- c("S1" = "#30123BFF", "S2" = "#30123BFF",
                 "B1" = "#1BD0D5FF", "B2" = "#1BD0D5FF",
                 "C1" = "#D2E935FF", "C2" = "#D2E935FF",
                 "P1" = "#DB3A07FF", "P2" = "#DB3A07FF")

site_shapes <- c("S1" = 15, "S2" = 16,
                 "B1" = 15, "B2" = 16,
                 "C1" = 15, "C2" = 16,
                 "P1" = 15, "P2" = 16)

iso_plotting %>%
  mutate(
    Site_group = substr(Site_code_new, 1, 1),       # S, B, C, P
    Number     = substr(Site_code_new, 2, 2),       # 1 or 2
    Legend_key = Site_code_new,                     # S1, S2, etc.
    Depth_type = sub(".*_", "", Site_CODE)          # extract depth after underscore
  ) %>%
  filter(Depth_type %in% c("0.1", "BOT")) |> 
  ggplot(aes(x = Date, y = D_excess,
             color = Legend_key,
             shape = Legend_key,
             linetype = Depth_type,
             group = interaction(Legend_key, Depth_type))) +
  geom_point(size = 3) +
  geom_line(size = 1.3) +
  labs(x = "Date", y = "Deuterium excess",
       color = "Site", shape = "Site", linetype = "Depth") +
  annotate("text", x = ymd("2024-06-01"), y = 18,
           label = "D excess = dD - 8*d18O",
           size = 5, color = "black", hjust = 0) +
  theme_bw() +
  theme(
    legend.position = "top",
    text = element_text(size = 18),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  ) +
  guides(color = guide_legend(nrow = 2, byrow = TRUE)) +
  scale_x_date(date_labels = "%b %Y ") +
  scale_color_manual(values = site_colors, breaks = iso_levels_sites) +
  scale_shape_manual(values = site_shapes, breaks = iso_levels_sites) +
  scale_linetype_manual(values = c(
    "0.1" = "solid",
    "1.5" = "dashed",
    "6" = "dotted",
    "9" = "dotdash",
    "BOT"   = "twodash"
  ))


```

Now Iso TS with all depths and rain

```{r}

############################# SOMETHING WRONG WITH RAIN SCALING RIGHT NOW ###########################################

iso_levels_sites <- c("S1","S2","B1","B2","C1","C2","P1","P2")

site_colors <- c("S1" = "#30123BFF", "S2" = "#30123BFF",
                 "B1" = "#1BD0D5FF", "B2" = "#1BD0D5FF",
                 "C1" = "#D2E935FF", "C2" = "#D2E935FF",
                 "P1" = "#DB3A07FF", "P2" = "#DB3A07FF")

site_shapes <- c("S1" = 15, "S2" = 16,
                 "B1" = 15, "B2" = 16,
                 "C1" = 15, "C2" = 16,
                 "P1" = 15, "P2" = 16)

# Build plotting dataset with rain
plot_data <- iso_plotting %>%
  full_join(hydro_data, by = "Date") %>%
  rename(Rain_mm = CCR_MetStation_daily_rain_mm) %>%
  filter(Date >= ymd("2024-05-01"),
         Date <= ymd("2025-05-01")) %>%
  mutate(
    Site_group = substr(Site_code_new, 1, 1),
    Number     = substr(Site_code_new, 2, 2),
    Legend_key = Site_code_new,
    Depth_type = sub(".*_", "", Site_CODE)   # extract depth after underscore
  )

# Scaling factor for rainfall bars
max_dexcess <- max(plot_data$D_excess, na.rm = TRUE)
max_rain    <- max(plot_data$Rain_mm, na.rm = TRUE)
scale_factor <- max_dexcess / max_rain

ggplot() +
  # Rain bars (no legend)
  geom_col(data = plot_data,
           aes(x = Date, y = Rain_mm * scale_factor),
           fill = "lightblue", width = 1,
           show.legend = FALSE) +

  # Isotope points and lines
  geom_point(data = plot_data,
             aes(x = Date, y = D_excess,
                 color = Legend_key,
                 shape = Legend_key,
                 group = interaction(Legend_key, Depth_type)),
             size = 3) +
  geom_line(data = plot_data,
            aes(x = Date, y = D_excess,
                color = Legend_key,
                linetype = Depth_type,
                group = interaction(Legend_key, Depth_type)),
            size = 1.3) +

  # Labels and annotation
  labs(x = "Date", y = "Deuterium excess",
       color = "Site", shape = "Site", linetype = "Depth") +
  annotate("text", x = ymd("2024-06-01"), y = 18,
           label = "D excess = dD - 8*d18O",
           size = 5, color = "black", hjust = 0) +

  # Theme
  theme_bw() +
  theme(
    legend.position = "top",
    text = element_text(size = 18),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  ) +
  guides(color = guide_legend(nrow = 2, byrow = TRUE)) +

  # Manual scales with enforced order
  scale_x_date(date_labels = "%b %Y ") +
  scale_color_manual(values = site_colors, breaks = iso_levels_sites) +
  scale_shape_manual(values = site_shapes, breaks = iso_levels_sites) +
  scale_linetype_manual(values = c(
     "0.1" = "solid",
    "1.5" = "dashed",
    "6" = "dotted",
    "9" = "dotdash",
    "BOT"   = "twodash"
  )) +

  # Secondary axis for rainfall
  scale_y_continuous(
    sec.axis = sec_axis(~ . / scale_factor, name = "Rainfall (mm)")
  )
```




isos with depth on Y 

```{r}
levels_db <- c("22 May", "19 Jun", "11 Jul", "14 Aug", "16 Sep", 
               "30 Sep", "28 Oct", "17 Dec", "26 Feb", "16 Apr")

#Stream to C1

iso_plotting |> 
  filter(!Site %in% c(50,88,90)) |> 
    mutate(Dry_start = ifelse(Depth_m == 0.1 & Site_code == "S1", Dry_start, NA),
         Dry_end = ifelse(Depth_m == 0.1 & Site_code == "S1", Dry_end, NA)) |> #so just one row has info for dry start and end, was having issues where laying multiple rectangles for more observations affected shading color
  mutate(Date1 = format(Date, "%d %b")) |> 
  ggplot(aes(x = Distance, y = Depth_m, fill = D_excess))+
  geom_rect(aes(xmin = Dry_start, xmax = Dry_end, ymin = -Inf, ymax = Inf), 
            alpha = 0.5, fill = "gray", color = NA )+ #color gets rid of border
  facet_wrap(~factor(Date1, levels = levels_db), scales = "fixed", nrow = 1)+
  geom_point(size = 3, shape = 21)+ #need shape here if not doing site type
  scale_y_reverse()+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 18),
                    legend.text = element_text(size = 12),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x= "Distance from Stream (m)",
       y = "Depth (m)", fill = "D excess")+
  scale_x_continuous(breaks = c(0, 150, 300)) +
  #scale_fill_gradient(low = "blue",  high ="red")
 scale_fill_gradient2(low = "blue",  high ="red", breaks = c(5,10,15),
                       midpoint = 10,  guide = "colourbar")


#all sites

iso_plotting |> 
  # filter(!Site %in% c(50,88,90)) |> 
    mutate(Dry_start = ifelse(Depth_m == 0.1 & Site_code == "S1", Dry_start, NA),
         Dry_end = ifelse(Depth_m == 0.1 & Site_code == "S1", Dry_end, NA)) |> #so just one row has info for dry start and end, was having issues where laying multiple rectangles for more observations affected shading color
  mutate(Date1 = format(Date, "%d %b")) |> 
  ggplot(aes(x = Distance, y = Depth_m, fill = D_excess))+
  geom_rect(aes(xmin = Dry_start, xmax = Dry_end, ymin = -Inf, ymax = Inf), 
            alpha = 0.5, fill = "gray", color = NA )+ #color gets rid of border
  facet_wrap(~factor(Date1, levels = levels_db), scales = "fixed", nrow = 1)+
  geom_point(size = 3, shape = 21)+ #need shape here if not doing site type
  scale_y_reverse()+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 18),
                    legend.text = element_text(size = 12),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x= "Distance from Stream (m)",
       y = "Depth (m)", fill = "D excess")+
  scale_x_continuous(breaks = c(0, 500, 1000, 1500))+  
  #scale_fill_gradient(low = "blue",  high ="red")
 scale_fill_gradient2(low = "blue",  high ="red", breaks = c(5,10,15),
                       midpoint = 10,  guide = "colourbar")



```





