---
title: "Sensor_Plotting"
output: html_document
date: "2025-11-24"
---


## Sensor figures

```{r}
#read in data
sensors <- read.csv("./Sensor_Data_compiled.csv") |> 
   mutate(Site_code = ifelse(Site == 101, "S1", NA),
         Site_code = ifelse(Site == 100, "S2", Site_code),
         Site_code = ifelse(Site == 98, "P1", Site_code),
         Site_code = ifelse(Site == 96, "P2", Site_code),
         Site_code = ifelse(Site == 94, "C1", Site_code),
         Site_code = ifelse(Site == 92, "C2", Site_code),
         Site_code = ifelse(Site == 90, "C3", Site_code),
         Site_code = ifelse(Site == 88, "C4", Site_code),
         Site_code = ifelse(Site == 50, "C50", Site_code)
         ) |> 
  mutate(Date = as.Date(Date)) |> 
    filter(Site != 94) #remove old site C1



depths <- read.csv("C:/Users/dwh18/Downloads/2024 spatial sampling - Site_Depths.csv") |> 
  dplyr::select(-10) |> 
  mutate(Date = mdy(Date)) |> 
  pivot_longer(-c(1), names_to = "Site_code", values_to = "Site_Max_Depth") 



sensors <- left_join(sensors, distances, by = c("Site_code", "Date")) |>
    mutate(Distance = Distance_ft*0.3048,
         Dry_start = Dry_start*0.3048,
         Dry_end = Dry_end*0.3048) |> 
  left_join(site_class, by = c("Site_code", "Date")) |> 
    left_join(depths, by = c("Site_code", "Date") ) |> 
  select(Reservoir, Site, Site_code, Site_Class, Date, Site_Max_Depth, Distance, Dry_start, Dry_end, Depth_m, Temp_C, DO_mgL, DOsat_percent, SpCond_uScm)


```


all variables by date plot 

```{r}

sensors |> 
  select(-DO_mgL) |> 
  pivot_longer(-c(1:10)) |> 
  # filter(name == "Temp_C") |> 
  ggplot(aes(x = Distance, y = value, fill = Depth_m,
             #shape = factor(Site_Class, levels = c("Stream", "Pool", "Cove", "Pelagic"))
             ))+
  geom_rect(aes(xmin = Dry_start, xmax = Dry_end, ymin = -Inf, ymax = Inf), 
            alpha = 0.1, fill = "gray", color = NA )+ #color gets rid of border
  facet_grid(name~Date, scales = "free_y")+
  geom_point(size = 3, shape = 21)+ #need shape here if not doing site type
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x= "Distance from Stream (m)",
       shape = "Site Type")+
  scale_x_continuous(breaks = c(0, 500, 1000, 1500))+ #c(250, 750)
  #scale_shape_manual(values = c(24, 22, 21, 25))+ #18, 15, 16, 17
  scale_fill_gradient2(low = "red",  high ="blue",
                       midpoint = 6,  guide = "colourbar", breaks = c(3,6,9, 15, 20))


```


zoom in on shallow sites

```{r}

#value on y
sensors |> 
  filter(!Site %in% c(50,88,90)) |> 
  select(-DO_mgL) |> 
  pivot_longer(-c(1:10)) |> 
  # filter(name == "Temp_C") |> 
  ggplot(aes(x = Distance, y = value, fill = Depth_m,
             #shape = factor(Site_Class, levels = c("Stream", "Pool", "Cove", "Pelagic"))
             ))+
  geom_rect(aes(xmin = Dry_start, xmax = Dry_end, ymin = -Inf, ymax = Inf), 
            alpha = 0.1, fill = "gray", color = NA )+ #color gets rid of border
  facet_grid(name~Date, scales = "free_y")+
  geom_point(size = 3, shape = 21)+ #need shape here if not doing site type
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x= "Distance from Stream (m)",
       shape = "Site Type")+
  scale_x_continuous(breaks = c(0, 150, 300))+ #c(250, 750)
  #scale_shape_manual(values = c(24, 22, 21, 25))+ #18, 15, 16, 17
  scale_fill_gradient2(low = "red",  high ="blue",
                       midpoint = 0.7,  guide = "colourbar", breaks = c(0,1,2,3))




```

 Depth on Y
 
```{r}
#depth on y
plunge_spcond_fig <- sensors |> 
  filter(!Site %in% c(50,88,90)) |> 
    mutate(Dry_start = ifelse(Depth_m == 0.1 & Site_code == "S1", Dry_start, NA),
         Dry_end = ifelse(Depth_m == 0.1 & Site_code == "S1", Dry_end, NA)) |> #so just one row has info for dry start and end, was having issues where laying multiple rectangles for more observations affected shading color
  select(-DO_mgL) |> 
  pivot_longer(-c(1:10)) |> 
  filter(name == "SpCond_uScm") |> 
  ggplot(aes(x = Distance, y = Depth_m, fill = value))+
  geom_rect(aes(xmin = Dry_start, xmax = Dry_end, ymin = -Inf, ymax = Inf), 
            alpha = 0.5, fill = "gray", color = NA )+ #color gets rid of border
  facet_grid(name~Date, scales = "free_y")+
  geom_point(size = 3, shape = 21)+ #need shape here if not doing site type
  scale_y_reverse()+
  theme_bw()+ theme(legend.position = "right", text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x= "Distance from Stream (m)",
       shape = "Site Type")+
  scale_x_continuous(breaks = c(0, 150, 300)) +
  #scale_fill_gradient(low = "blue",  high ="red")
 scale_fill_gradient2(low = "blue",  high ="red",
                       midpoint = 75,  guide = "colourbar")

plunge_spcond_fig


plunge_temp_fig <- sensors |> 
  filter(!Site %in% c(50,88,90)) |> 
  mutate(Dry_start = ifelse(Depth_m == 0.1 & Site_code == "S1", Dry_start, NA),
         Dry_end = ifelse(Depth_m == 0.1 & Site_code == "S1", Dry_end, NA)) |> #so just one row has info for dry start and end, was having issues where laying multiple rectangles for more observations affected shading color
  select(-DO_mgL) |> 
  pivot_longer(-c(1:10)) |> 
  filter(name == "Temp_C") |> 
  ggplot(aes(x = Distance, y = Depth_m, fill = value))+
  geom_rect(aes(xmin = Dry_start, xmax = Dry_end, ymin = -Inf, ymax = Inf), 
            alpha = 0.5, fill = "gray", color = NA )+ #color gets rid of border
  facet_grid(name~Date, scales = "free_y")+
  geom_point(size = 3, shape = 21)+ #need shape here if not doing site type
  scale_y_reverse()+
  theme_bw()+ theme(legend.position = "right", text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x= "Distance from Stream (m)",
       shape = "Site Type")+
  scale_x_continuous(breaks = c(0, 150, 300)) +
  #scale_fill_gradient(low = "red",  high ="blue")
 scale_fill_gradient2(low = "blue",  high ="red",
                       midpoint = 15,  guide = "colourbar")

plunge_temp_fig


library(patchwork)
plunge_spcond_fig / plunge_temp_fig


```
 
## MS figures 
 
Stream to C1 cond for Main MS
 Clean up by date format && add lines for surface of water and max depth
 
```{r}

### Cond for comm meeting
levels_db <- c("22 May", "19 Jun", "11 Jul", "14 Aug", "16 Sep", 
               "30 Sep", "28 Oct", "17 Dec", "26 Feb", "16 Apr")

sensors |> 
  filter(!Site %in% c(50,88,90)) |> 
    mutate(Dry_start = ifelse(Depth_m == 0.1 & Site_code == "S1", Dry_start, NA),
         Dry_end = ifelse(Depth_m == 0.1 & Site_code == "S1", Dry_end, NA)) |> #so just one row has info for dry start and end, was having issues where laying multiple rectangles for more observations affected shading color
  select(-DO_mgL) |> 
  mutate(Date1 = format(Date, "%d %b")) |> 
  ggplot(aes(x = Distance, y = Depth_m, fill = SpCond_uScm))+
  geom_hline(yintercept = 0, color = "blue")+ # line for surface of the water
  geom_rect(aes(xmin = Dry_start, xmax = Dry_end, ymin = -Inf, ymax = Inf), 
            alpha = 1, fill = "gray", color = NA )+ #Line for dry reach; color gets rid of border
    geom_line(aes(y = Site_Max_Depth+0.1), color = "brown")+ #line for max depth
  facet_wrap(~factor(Date1, levels = levels_db), scales = "fixed", nrow = 1)+
  geom_point(size = 3, shape = 21)+ #need shape here if not doing site type
  scale_y_reverse(breaks = c(0, 0.5, 1, 1.5, 2, 2.5))+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 14),
                    legend.text = element_text(size = 12),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x= "Distance from Stream (m)",
       y = "Depth (m)", fill = "Sp. Cond (uS/cm)")+
  scale_x_continuous(breaks = c(0, 150, 300)) +
  #scale_fill_gradient(low = "blue",  high ="red")
 scale_fill_gradient2(low = "blue",  high ="red",
                       midpoint = 75,  guide = "colourbar")

#ggsave("MS_draft_figures/SpCond_S1-C1.png", width = 9.5, height = 5.5, units = "in")


##sensors for AGU

levels_agu <- c("22 May",  "16 Sep", 
               "30 Sep", "26 Feb", "16 Apr")

sensors |> 
  filter(!Site %in% c(50,88,90)) |> 
    mutate(Dry_start = ifelse(Depth_m == 0.1 & Site_code == "S1", Dry_start, NA),
         Dry_end = ifelse(Depth_m == 0.1 & Site_code == "S1", Dry_end, NA)) |> #so just one row has info for dry start and end, was having issues where laying multiple rectangles for more observations affected shading color
  select(-DO_mgL) |> 
  mutate(Date1 = format(Date, "%d %b")) |> 
  filter(Date1 %in% levels_agu) |> 
  ggplot(aes(x = Distance, y = Depth_m, fill = SpCond_uScm))+
  geom_rect(aes(xmin = Dry_start, xmax = Dry_end, ymin = -Inf, ymax = Inf), 
            alpha = 1, fill = "gray", color = NA )+ #Line for dry reach; color gets rid of border
  facet_wrap(~factor(Date1, levels = levels_agu), scales = "fixed", nrow = 1)+
  geom_point(size = 3, shape = 21)+ #need shape here if not doing site type
  scale_y_reverse(breaks = c(0, 0.5, 1, 1.5, 2, 2.5))+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 14),
                    legend.text = element_text(size = 12),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x= "Distance from Stream (m)",
       y = "Depth (m)", fill = "Sp. Cond (uS/cm)")+
  scale_x_continuous(breaks = c(0, 150, 300)) +
  #scale_fill_gradient(low = "blue",  high ="red")
 scale_fill_gradient2(low = "blue",  high ="red",
                       midpoint = 75,  guide = "colourbar")



```
 

By date profiles for Temp, DO, Cond

```{r}

##COnd 
SpCond_fig <- sensors |> 
      filter(!is.na(SpCond_uScm),
             SpCond_uScm < 200) |> 
    mutate(Dry_start = ifelse(Depth_m == 0.1 & Site_code == "S1", Dry_start, NA),
         Dry_end = ifelse(Depth_m == 0.1 & Site_code == "S1", Dry_end, NA)) |> #so just one row has info for dry start and end, was having issues where laying multiple rectangles for more observations affected shading color
  ggplot(aes(x = Distance, y = Depth_m, color = SpCond_uScm))+
  geom_rect(aes(xmin = Dry_start, xmax = Dry_end, ymin = -Inf, ymax = Inf), 
            alpha = 1, fill = "gray", color = NA )+ #color gets rid of border
  facet_wrap(~Date, scales = "fixed", nrow = 1)+
  geom_point(size = 3)+
  scale_y_reverse()+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x= "Distance from Stream (m)", y = "Depth (m)", color = "Sp. Cond (uS/cm)")+
  scale_x_continuous(breaks = c(0, 600, 1200)) +
 scale_color_gradient2(low = "blue",  high ="red", breaks = c(25,75,125),
                       midpoint = 75,  guide = "colourbar")

SpCond_fig


##Temp 
Temp_fig <- sensors |> 
  # filter(!Site %in% c(88,50)) |> 
    filter(!is.na(Temp_C)) |> 
    mutate(Dry_start = ifelse(Depth_m == 0.1 & Site_code == "S1", Dry_start, NA),
         Dry_end = ifelse(Depth_m == 0.1 & Site_code == "S1", Dry_end, NA)) |> #so just one row has info for dry start and end, was having issues where laying multiple rectangles for more observations affected shading color
  ggplot(aes(x = Distance, y = Depth_m, color = Temp_C))+
  geom_rect(aes(xmin = Dry_start, xmax = Dry_end, ymin = -Inf, ymax = Inf), 
            alpha = 1, fill = "gray", color = NA )+ #color gets rid of border
  facet_wrap(~Date, scales = "fixed", nrow = 1)+
  geom_point(size = 3)+ 
  scale_y_reverse()+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x= "Distance from Stream (m)", y = "Depth (m)", color = "Temp (C)")+
  scale_x_continuous(breaks = c(0, 600, 1200)) +
 scale_color_gradient2(low = "blue",  high ="red", breaks = c(5,15,25),
                       midpoint = 15,  guide = "colourbar")

Temp_fig


##DO 
DO_fig <- sensors |> 
  filter(!is.na(DOsat_percent)) |> 
    mutate(Dry_start = ifelse(Depth_m == 0.1 & Site_code == "S1", Dry_start, NA),
         Dry_end = ifelse(Depth_m == 0.1 & Site_code == "S1", Dry_end, NA)) |> #so just one row has info for dry start and end, was having issues where laying multiple rectangles for more observations affected shading color
  ggplot(aes(x = Distance, y = Depth_m, color = DOsat_percent))+
  geom_rect(aes(xmin = Dry_start, xmax = Dry_end, ymin = -Inf, ymax = Inf), 
            alpha = 1, fill = "gray", color = NA )+ #color gets rid of border
  facet_wrap(~Date, scales = "fixed", nrow = 1)+
  geom_point(size = 3)+ 
  scale_y_reverse()+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x= "Distance from Stream (m)", y = "Depth (m)", color = "DO (% sat)")+
  scale_x_continuous(breaks = c(0, 600, 1200)) +
 scale_color_gradient2(low = "blue",  high ="red", breaks = c(25,75,125),
                       midpoint = 75,  guide = "colourbar")

DO_fig

## put them together
library(patchwork)
sensors_SI_fig <- Temp_fig / DO_fig / SpCond_fig

sensors_SI_fig

# ggsave("MS_draft_figures/sensors_SI_fig.png", sensors_SI_fig, width = 9.5, height = 10, units = "in")

plotly::ggplotly(Temp_fig_noPs)


```










