---
title: "EEMs exploration"
author: "Dexter Howard"
date: "2023-06-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Read in packages 

```{r, include = F}
library(tidyverse)
library(lubridate) # for changing date format in dataframe: functions ymd() and others 
library(scales) #for date format on plots
library(patchwork) #arrange figures w/ slashes and lines
library(plotly)

```

## Get data 

```{r}
# eems_edi <- read_csv("https://pasta.lternet.edu/package/data/eml/edi/841/1/f63272976bcd151f8e879cbd14d9a9ce")

## Full eems data set 
eems <- read.csv("./../EEMs_Results.csv")
head(eems)

## EEMs plunge point data subset 
eems_cove <- read.csv("./../EEMs_Results_CCR_plungepoint_subset.csv")

```

## Stream vs Lake plots 

```{r}

##Get just CCR data from streams and pelagic site 
ccreems <- eems %>%
  slice(-c(114:116, 122,123,125, 126)) %>% #removing cove sites that have non numeric site number
  mutate(Site = as.numeric(Site)) %>% 
  filter(Reservoir == "CCR")

## Plot just HIX from the streams 
ccreems %>% 
  mutate(Depth_m = ifelse(Depth_m == 21, 20, Depth_m)) %>%
  mutate(Group = ifelse(Site == 50, "Dam", "Stream")) %>%
  # filter(Depth_m != 6) %>%
  mutate(Site_Depth = ifelse(Site == 50, Depth_m, Site)) %>%
  filter(Group == "Stream") %>%
  ggplot(aes(x = Date, y = HIX))+
  geom_point()+
  ylim(1.1,10.7)+
  # facet_wrap(~Site, ncol = 1)+
  facet_wrap(~Site_Depth, ncol = 1)+
  ggtitle("CCR Stream HIX")+
  # scale_x_date(breaks = "1 month", date_labels = "%b %y")+
  theme_bw()+
  theme(text = element_text(size = 16))

## Plot all variables from the streams 
ccreems %>% 
  mutate(Depth_m = ifelse(Depth_m == 21, 20, Depth_m)) %>%
  mutate(Group = ifelse(Site == 50, "Dam", "Stream")) %>%
  filter(Depth_m != 6) %>%
  mutate(Site_Depth = ifelse(Site == 50, Depth_m, Site)) %>%
  filter(Group == "Stream") %>%
  mutate(Site = ifelse(Site %in% c(100, 101), 100, Site),
         Site = ifelse(Site %in% c(300,301), 300, Site)) %>% 
  select(2, 4, 11:28) %>% 
  pivot_longer(-c(1:2)) %>% 
  # filter(Site %in% c(300, 301)) %>% 
  ggplot(aes(x = mdy(Date), y = value, color = as.factor(Site)))+
  geom_point()+
  geom_line()+
  facet_wrap(~name, scales = "free_y")
  
  
## Plot all variables from the dam
ccreems %>% 
  mutate(Depth_m = ifelse(Depth_m == 21, 20, Depth_m)) %>%
  mutate(Group = ifelse(Site == 50, "Dam", "Stream")) %>%
  # filter(Depth_m != 6) %>%
  mutate(Site_Depth = ifelse(Site == 50, Depth_m, Site)) %>%
  filter(Group == "Dam") %>%
  select(3, 4, 11:28) %>% 
  pivot_longer(-c(1:2)) %>% 
  ggplot(aes(x = mdy(Date), y = value, color = Depth_m))+
  geom_point()+
  geom_line()+
  facet_wrap(~name, scales = "free_y")


```


## Cove plotting

```{r}
## June 1 eems depth profile 
eems %>% 
  select(-FLAG, -Notes_flag) %>% 
  pivot_longer(11:28) %>% 
  mutate(Date = mdy(Date)) %>% 
  filter( Site == 50,
          Date == ymd("2023-06-01")
          ) %>% 
  ggplot(aes(x = value, y = as.numeric(Depth_m)))+
  geom_point()+
  scale_y_reverse()+
  ggtitle("1 June 2023 Pelagic depth profile")+
  facet_wrap(~name, scales = "free_x")

## 4 may eems depth profile 
eems %>% 
  select(-FLAG, -Notes_flag) %>% 
  pivot_longer(11:28) %>% 
  mutate(Date = mdy(Date)) %>% 
  filter( Site == 50,
          Date == ymd("2023-05-04")
          ) %>% 
  ggplot(aes(x = value, y = as.numeric(Depth_m)))+
  geom_point()+
  scale_y_reverse()+
  ggtitle("4 May 2023 Pelagic depth profile")+
  facet_wrap(~name, scales = "free_x")


#### SMB plunge june 1st
smb_1jun <- eems_cove %>% 
  select(-FLAG, -Notes_flag) %>% 
  pivot_longer(13:30) %>% 
  mutate(Date = mdy(Date)) %>% 
  filter(
    Site_num %in% c(3000,300,30),
      # Site_num %in% c(1000,10),
    Date == ymd("2023-06-01")
         ) %>% 
  mutate(Distance = ifelse(Site_num == 3000, 0, NA),
         Distance = ifelse(Site_num == 300, 65, Distance),
         Distance = ifelse(Site_num == 30, 430, Distance)
         ) %>% 
  #next two lines are to format for poster
  filter(name == "HIX") %>%
  mutate(name = "Inflow 300 - 1 June 2023") %>%
  ggplot(aes(x = Distance, y = value, col = Depth_name))+
    geom_point(size = 3)+
    geom_line(size = 1)+
  labs(x = "Distance from stream site (m)",
       y = "HIX",
       #y = "variable",
       color = "Sample Depth")+
  facet_wrap(~name, scales = "free_y")+
  ylim(1,7)+
  theme_bw()+
  theme(text = element_text(size=21),
        axis.text = element_text(size=21),
        legend.position = "top")



#SMB plunge may 4th
smb_4may <- eems_cove %>% 
  select(-FLAG, -Notes_flag) %>% 
  pivot_longer(13:30) %>% 
  mutate(Date = mdy(Date)) %>% 
  filter(
    Site_num %in% c(3000,300,30),
      # Site_num %in% c(1000,10),
    Date == ymd("2023-05-04")
         ) %>% 
  mutate(Distance = ifelse(Site_num == 3000, 0, NA),
         Distance = ifelse(Site_num == 300, 65, Distance),
         Distance = ifelse(Site_num == 30, 430, Distance)
         ) %>% 
  #next two lines are to format for poster
  filter(name == "HIX") %>% 
  mutate(name = "Inflow 300 - 4 May 2023") %>% 
  ggplot(aes(x = Distance, y = value, col = Depth_name))+
    geom_point(size = 3)+
  geom_line(size = 1)+
  labs(x = "Distance from stream site (m)",
       y = "HIX",
       color = "Sample Depth")+
  facet_wrap(~name, scales = "free_y")+
  ylim(1,7)+
  theme_bw()+
  theme(text = element_text(size=21),
        axis.text = element_text(size=21),
        legend.position = "top")

#HPB plunge june 1
hpb_1jun <- eems_cove %>% 
  select(-FLAG, -Notes_flag) %>% 
  pivot_longer(13:30) %>% 
  mutate(Date = mdy(Date)) %>% 
  filter(
    # Site_num %in% c(3000,300,30),
      Site_num %in% c(1000,10),
    Date == ymd("2023-06-01")
         ) %>% 
  mutate(Distance = ifelse(Site_num == 1000, 0, NA),
         Distance = ifelse(Site_num == 10, 249, Distance)
         ) %>% 
  #next two lines are to format for poster
  filter(name == "HIX") %>% 
  mutate(name = "Inflow 100 - 1 June 2023") %>% 
  ggplot(aes(x = Distance, y = value, col = Depth_name))+
    geom_point(size = 3)+
    geom_line(size = 1)+
  labs(x = "Distance from stream site (m)",
       y = "HIX",
       color = "Sample Depth")+
  facet_wrap(~name, scales = "free_y")+
  ylim(1,7)+
  theme_bw()+
  theme(text = element_text(size=21),
        axis.text = element_text(size=21),
        legend.position = "top")

smb_1jun | smb_4may | hpb_1jun

#ggsave("./ESAposter_plunge.png", width = 23, height = 7, units = "in")

### SMB spot distances 
# 23m from flowmate spot to pool A (large trees dam)
# 65m  from flowmate spot to pool B (just past downed trees)
# 430m from flowmate to cove sample sites 

```

## Cove plotting w/ pelagic 

```{r}

## SMB 4 may 2023
smb4may23 <- eems %>% 
  mutate(Date = mdy(Date)) %>% 
  filter(Reservoir == "CCR",
         Date == ymd("2023-05-04")) %>% 
  select(Site, Date, Depth_m, HIX) %>% 
  mutate(Site_num = ifelse(Site == 301, 3000, NA),
         Site_num = ifelse(Site == "300_COVE", 30, Site_num)
         ) %>% 
    mutate(Distance = ifelse(Site_num == 3000, 0, NA),
           Distance = ifelse(Site_num == 30, 430, Distance),
           Distance = ifelse(Site == 50, 17854, Distance) #17424 ft plus the 430
         ) %>% 
  filter(!is.na(Distance)) %>% 
  filter(Distance < 900) %>% 
  group_by(Site, Depth_m) %>% 
  summarise(across(.cols = where(is.numeric), .fns = ~mean(.x, na.rm = TRUE)), .groups = "drop") %>% #average dups
  mutate(Depth_m = ifelse(Depth_m == "PD", 1.5, Depth_m),
         Depth_m = ifelse(Depth_m == "SURF", 0.1, Depth_m)) %>% 
  mutate(Depth_levels = fct_relevel(Depth_m, "0.1", "1.5", "9")) %>% #making depth factors by level so appear in order for plot below
  ggplot(aes(x = (Distance*0.3048), y = HIX, color = Depth_levels))+
    geom_point(size = 4)+
    geom_line(size = 1)+
  labs(x = "Distance from stream site (m)",
       y = "HIX",
       color = "Sample Depth")+
  ylim(1,7)+
  ggtitle("Stream 300 - 4 May 2023")+
  theme_bw()+
  theme(text = element_text(size=21),
        axis.text = element_text(size=21),
        legend.position = "top")+
  scale_color_manual(values = c("0.1" = "#000000", "1.5" = "#E69F00", "9" = "#009E73"))
  
smb4may23

pelagic4may23 <- eems %>% 
  mutate(Date = mdy(Date)) %>% 
  filter(Reservoir == "CCR",
         Date == ymd("2023-05-04"),
         Site ==50) %>% 
  select(Site, Date, Depth_m, HIX) %>% 
  group_by(Site, Depth_m) %>% 
  summarise(across(.cols = where(is.numeric), .fns = ~mean(.x, na.rm = TRUE)), .groups = "drop") %>% #average dups
  mutate(Depth_levels = fct_relevel(Depth_m, "0.1", "1.5", "9")) %>% #making depth factors by level so appear in order for plot below
  mutate(Site = "Reservoir Deepest Site") %>% 
  ggplot(aes(x = (Site), y = HIX))+
    geom_boxplot()+
    geom_point(aes(x = (Site), y = HIX, color = Depth_levels), size = 4)+
  labs(x = "Reservoir \n Deepest Site",
       y = element_blank(),
       #y = "HIX",
       color = "Sample Depth")+
  ylim(1,7)+
  ggtitle("4 May 2023")+
  theme_bw()+
  theme(text = element_text(size=21),
        axis.text = element_text(size=21),
        axis.text.x = element_blank(),
        legend.position = "top")+
  scale_color_manual(values = c("0.1" = "#000000", "1.5" = "#E69F00", "9" = "#009E73"))
  
pelagic4may23



## SMB 1 June 2023
smb1june23 <- eems %>% 
  mutate(Date = mdy(Date)) %>% 
  filter(Reservoir == "CCR",
         Date == ymd("2023-06-01")) %>% 
  select(Site, Date, Depth_m, HIX) %>% 
  mutate(Site_num = ifelse(Site == 300, 3000, NA),
         Site_num = ifelse(Site == "300_POOL", 300, Site_num),
         Site_num = ifelse(Site == "300_COVE", 30, Site_num)
         ) %>% 
    mutate(Distance = ifelse(Site_num == 3000, 0, NA),
           Distance = ifelse(Site_num == 300, 65, Distance),
           Distance = ifelse(Site_num == 30, 430, Distance),
           Distance = ifelse(Site == 50, 17854, Distance) #17424 ft plus the 430
         ) %>% 
  filter(!is.na(Distance)) %>% 
   filter(Distance < 900) %>% 
  group_by(Site, Depth_m) %>% 
  summarise(across(.cols = where(is.numeric), .fns = ~mean(.x, na.rm = TRUE)), .groups = "drop") %>% #average dups
  mutate(Depth_m = ifelse(Depth_m == "BOT", 1.5, Depth_m),
         Depth_m = ifelse(Depth_m == "SURF", 0.1, Depth_m)) %>% 
  mutate(Depth_levels = fct_relevel(Depth_m, "0.1", "1.5", "6", "9", "20")) %>% #making depth factors by level so appear in order for plot below
  ggplot(aes(x = (Distance*0.3048), y = HIX, color = Depth_levels))+
    geom_point(size = 4)+
    geom_line(size = 1)+
  labs(x = "Distance from stream site (m)",
       y = element_blank(),
       #y = "HIX",
       color = "Sample Depth")+
  ylim(1,7)+
  ggtitle("Stream 300 - 1 June 2023")+
  theme_bw()+
  theme(text = element_text(size=21),
        axis.text = element_text(size=21),
        legend.position = "top")+
  scale_color_manual(values = c("0.1" = "#000000", "1.5" = "#E69F00", "6" = "#56B4E9", "9" = "#009E73", "20" = "#F0E442"))
  
smb1june23

pelagic1june23 <- eems %>% 
  mutate(Date = mdy(Date)) %>% 
  filter(Reservoir == "CCR",
         Date == ymd("2023-06-01"),
         Site ==50) %>% 
  select(Site, Date, Depth_m, HIX) %>% 
  group_by(Site, Depth_m) %>% 
  summarise(across(.cols = where(is.numeric), .fns = ~mean(.x, na.rm = TRUE)), .groups = "drop") %>% #average dups
  mutate(Depth_levels = fct_relevel(Depth_m, "0.1", "1.5", "6", "9", "20")) %>% #making depth factors by level so appear in order for plot below
  mutate(Site = "Reservoir Deepest Site") %>% 
ggplot(aes(x = (Site), y = HIX))+
    geom_boxplot()+
    geom_point(aes(x = (Site), y = HIX, color = Depth_levels), size = 4)+
  labs(x = "Reservoir \n Deepest Site",
       y = element_blank(),
       #y = "HIX",
       color = "Sample Depth")+
  ylim(1,7)+
  ggtitle("1 June 2023")+
  theme_bw()+
  theme(text = element_text(size=21),
        axis.text = element_text(size=21),
        axis.text.x = element_blank(),
        legend.position = "top")+
  scale_color_manual(values = c("0.1" = "#000000", "1.5" = "#E69F00", "6" = "#56B4E9", "9" = "#009E73", "20" = "#F0E442")) 
  
pelagic1june23
 
## HPB 1 June 2023
hpb1june23 <- eems %>% 
  mutate(Date = mdy(Date)) %>% 
  filter(Reservoir == "CCR",
         Date == ymd("2023-06-01")) %>% 
  select(Site, Date, Depth_m, HIX) %>% 
  mutate(Site_num = ifelse(Site == 100, 1000, NA),
         Site_num = ifelse(Site == "100_COVE", 10, Site_num)
         ) %>% 
    mutate(Distance = ifelse(Site_num == 1000, 0, NA),
           Distance = ifelse(Site_num == 10, 249, Distance),
           Distance = ifelse(Site == 50, 3749, Distance) #3500 ft plus the 249
         ) %>% 
  filter(!is.na(Distance)) %>% 
  filter(Distance < 900) %>% 
  group_by(Site, Depth_m) %>% 
  summarise(across(.cols = where(is.numeric), .fns = ~mean(.x, na.rm = TRUE)), .groups = "drop") %>% #average dups
  mutate(Depth_m = ifelse(Depth_m == "BOT", 1.5, Depth_m),
         Depth_m = ifelse(Depth_m == "SURF", 0.1, Depth_m)) %>% 
  mutate(Depth_levels = fct_relevel(Depth_m, "0.1", "1.5", "6", "9", "20")) %>% #making depth factors by level so appear in order for plot below
  ggplot(aes(x = (Distance*0.3048), y = HIX, color = Depth_levels))+
    geom_point(size = 4)+
    geom_line(size = 1)+
  labs(x = "Distance from stream site (m)",
       y = element_blank(),
       #y = "HIX",
       color = "Sample Depth")+
  ylim(1,7)+
  ggtitle("Stream 100 - 1 June 2023")+
  theme_bw()+
  theme(text = element_text(size=21),
        axis.text = element_text(size=21),
        legend.position = "top")+
  scale_color_manual(values = c("0.1" = "#000000", "1.5" = "#E69F00", "6" = "#56B4E9", "9" = "#009E73", "20" = "#F0E442")) 
  
hpb1june23 


## combo plot

smb4may23  | smb1june23 | hpb1june23 


smb4may23 + pelagic4may23 + smb1june23 + hpb1june23 + pelagic1june23 + plot_layout(widths = c(2,1,2,2,1))

ggsave("./ESAposter_plunge_V3.png", width = 23, height = 7, units = "in")



```


## HIX plot on poster

```{r}

ccreems <- read_csv("C:/Users/dwh18/OneDrive/Desktop/EEMs_Correction_Folder/EEMs_Results.csv")
head(ccreems)

ccreems <- ccreems %>% 
  filter(Reservoir == "CCR") %>% 
  mutate(Date = mdy(Date))

# ccreems <- left_join(chem, ccreems, by = c("DateTime" = "Date"))

stream_HIX <- ccreems %>% 
  mutate(Depth_m = ifelse(Depth_m == 21, 20, Depth_m)) %>%
  mutate(Group = ifelse(Site == 50, "Dam", "Stream")) %>%
  filter(Depth_m != 6) %>%
  mutate(Site_Depth = ifelse(Site == 50, Depth_m, Site)) %>%
  filter(Group == "Stream") %>%
  ggplot(aes(x = Date, y = HIX))+
  geom_point()+
  ylim(1.1,10.7)+
  # facet_wrap(~Site, ncol = 1)+
  facet_wrap(~Site_Depth, ncol = 1)+
  ggtitle("CCR Stream HIX")+
  # scale_x_date(breaks = "1 month", date_labels = "%b %y")+
  theme_bw()+
  scale_x_date(date_labels = "%b %y")+
  theme(text = element_text(size = 16))

stream_HIX_b <- ccreems %>% 
  mutate(Depth_m = ifelse(Depth_m == 21, 20, Depth_m)) %>%
  mutate(Group = ifelse(Site == 50, "Dam", "Stream")) %>%
  filter(Site != 201) %>%
  mutate(Site_Depth = ifelse(Site == 50, Depth_m, Site)) %>%
  filter(Group == "Stream") %>%
  mutate(Site = ifelse(Site == 101, 100, Site),
         Site = ifelse(Site == 301, 300, Site)) %>% 
  ggplot(aes(x = Date, y = HIX, color = as.factor(Site)))+
  geom_point(size=4)+
  geom_line(size=1)+
  labs(color = "Stream Site",
       y = "HIX",
       x = element_blank())+
  ylim(1.1,10.7)+
  # facet_wrap(~Site, ncol = 1)+
  # facet_wrap(~Site_Depth, ncol = 1)+
  # ggtitle("CCR Stream HIX")+
  # scale_x_date(breaks = "1 month", date_labels = "%b %y")+
  theme_bw()+
   ggtitle("A) Stream HIX")+
  scale_x_date(date_labels = "%b %y")+
  theme(text = element_text(size = 21),
        legend.position = "top",
        legend.text = element_text(size = 18),
        axis.text = element_text(size = 21))+
  scale_color_manual(values = c("100" = "#0072B2", "300" = "#D55E00", "400" = "#CC79A7", "500" = "#999999"  ))


res_HIX <- ccreems %>% 
  mutate(Depth_m = ifelse(Depth_m == 21, 20, Depth_m)) %>%
  mutate(Group = ifelse(Site == 50, "Dam", "Stream")) %>%
  # filter(Depth_m != 6) %>%
  mutate(Site_Depth = ifelse(Site == 50, Depth_m, Site)) %>%
  filter(Group == "Dam") %>%
  ggplot(aes(x = Date, y = HIX))+
  geom_point()+
  ylim(1.1,10.7)+
  # facet_wrap(~Site, ncol = 1)+
  facet_wrap(~Site_Depth, ncol = 1)+
  # ggtitle("CCR Stream HIX")+
  # scale_x_date(breaks = "1 month", date_labels = "%b %y")+
  theme_bw()+
  scale_x_date(date_labels = "%b %y")+
  theme(text = element_text(size = 16))

res_HIX_b <- ccreems %>% 
  mutate(Depth_m = ifelse(Depth_m == 21, 20, Depth_m)) %>%
  mutate(Group = ifelse(Site == 50, "Dam", "Stream")) %>%
  # filter(Depth_m != 6) %>%
  mutate(Site_Depth = ifelse(Site == 50, Depth_m, Site)) %>%
  filter(Group == "Dam") %>%
  ggplot(aes(x = Date, y = HIX, color = as.factor(Depth_m)))+
  geom_point(size=4)+
  geom_line(size=1)+
  labs(color = "Depth (m)",
       y = "HIX",
       x = element_blank())+
  ylim(1.1,10.7)+
  # facet_wrap(~Site, ncol = 1)+
  # facet_wrap(~Site_Depth, ncol = 1)+
  # ggtitle("CCR Stream HIX")+
  # scale_x_date(breaks = "1 month", date_labels = "%b %y")+
  theme_bw()+
  ggtitle("B) Reservoir HIX")+
  scale_x_date(date_labels = "%b %y")+
  theme(text = element_text(size = 21),
        legend.position = "top",
        legend.text = element_text(size = 18),
        axis.text = element_text(size = 21))+
  scale_color_manual(values = c("0.1" = "#000000", "1.5" = "#E69F00", "6" = "#56B4E9", "9" = "#009E73", "20" = "#F0E442"))

# stream_HIX_b | res_HIX_b
# ggsave("./ESA_figures/HIX_combo.png", width = 21, height = 7, units = "in")

## CV calcs
stream_HIX_CV <- ccreems %>% 
  mutate(Depth_m = ifelse(Depth_m == 21, 20, Depth_m)) %>%
  mutate(Group = ifelse(Site == 50, "Dam", "Stream")) %>%
  filter(Site != 201) %>%
  mutate(Site_Depth = ifelse(Site == 50, Depth_m, Site)) %>%
  filter(Group == "Stream") %>%
  mutate(Site = ifelse(Site == 101, 100, Site),
         Site = ifelse(Site == 301, 300, Site)) %>% 
  select(Site, HIX) %>% 
  group_by(Site) %>% 
  summarize(mean = mean(HIX, na.rm = T),
            sd = sd(HIX, na.rm = T)) %>% 
  mutate(CV = sd/mean) %>% 
  rename(Depth_m = Site)


res_HIX_CV <- ccreems %>% 
  mutate(Depth_m = ifelse(Depth_m == 21, 20, Depth_m)) %>%
  mutate(Group = ifelse(Site == 50, "Dam", "Stream")) %>%
  # filter(Depth_m != 6) %>%
  mutate(Site_Depth = ifelse(Site == 50, Depth_m, Site)) %>%
  filter(Group == "Dam") %>% 
  select(Depth_m, HIX) %>% 
  group_by(Depth_m) %>% 
  summarize(mean = mean(HIX, na.rm = T),
            sd = sd(HIX, na.rm = T)) %>% 
  mutate(CV = sd/mean)

HIX_CV_plotting <- rbind(stream_HIX_CV, res_HIX_CV) %>% 
  mutate(Class = ifelse(Depth_m < 50, "Reservoir", "Stream")) %>% 
  select(Class,  Depth_m, mean, sd, CV)
  

level_order <- c("Stream", "Reservoir")
HIX_cv_plot <- HIX_CV_plotting %>% 
  ggplot(aes(x = Class, y = CV))+
  geom_boxplot()+
  geom_point(aes(x = as.factor(Class), y = CV, color = as.factor(Depth_m)), position = position_jitter(), size = 4)+
  labs(y = "HIX CV", x = element_blank())+
  ggtitle("C) HIX CV")+
  scale_x_discrete(limits = level_order) +
  theme_bw()+
  theme(text = element_text(size = 21),
        legend.position = "none",
        legend.text = element_text(size = 18),
        axis.text = element_text(size = 21))+
  scale_color_manual(values = c("0.1" = "#000000", "1.5" = "#E69F00", "6" = "#56B4E9", "9" = "#009E73", "20" = "#F0E442",
                                 "100" = "#0072B2", "300" = "#D55E00", "400" = "#CC79A7", "500" = "#999999"  ))

  
stream_HIX_b | res_HIX_b | HIX_cv_plot
ggsave("./HIX_combo.png", width = 23, height = 7.5, units = "in")


```


## DOC plots 

```{r}
chem <- read_csv("C:/Users/dwh18/OneDrive/Desktop/R_Projects/FCR_Metabolism/Data/EDI2023/FCR_chem_2022.csv")

chem %>% 
  filter(Reservoir == "CCR",
         Site %in% c(50,51),
         Depth_m %in% c(0.1,1.5,6,9, 20,21),
         DateTime >= ymd("2021-01-01")) %>% 
  # select(Reservoir, Site, DateTime, Depth_m, TN_ugL, TP_ugL, NO3NO2_ugL, NH4_ugL, SRP_ugL) %>% 
    select(Reservoir, Site, DateTime, Depth_m, DOC_mgL) %>% 
  pivot_longer(-c(1:4)) %>% 
  ggplot(aes(x=DateTime, y = value, col = as.factor(Depth_m)))+
  geom_point()+
  # geom_vline(xintercept = ymd_hms("2021-08-19 00:00:00"))+   
  # geom_vline(xintercept = ymd_hms("2021-09-23 00:00:00"))+   
  # geom_vline(xintercept = ymd_hms("2022-11-17 00:00:00"))+  
  facet_wrap(~name, ncol = 1, scales = "free_y")

chem %>% 
  filter(Reservoir == "CCR",
         Site > 51,
         DateTime >= ymd("2021-01-01")) %>% 
  mutate(Site_filt = ifelse(Site >= 100 & Site <200, 100, NA),
         Site_filt = ifelse(Site >= 200 & Site <300, 200, Site_filt),
         Site_filt = ifelse(Site >= 300 & Site <400, 300, Site_filt),
         Site_filt = ifelse(Site >= 400 & Site <500, 400, Site_filt),
         Site_filt = ifelse(Site >= 500, 500, Site_filt)
         ) %>% 
  filter(Site_filt > 200) %>%
  # select(Reservoir, Site_filt, DateTime, Depth_m, TN_ugL, TP_ugL, NO3NO2_ugL, NH4_ugL, SRP_ugL) %>% 
   select(Reservoir, Site_filt, DateTime, Depth_m, DOC_mgL) %>% 
  filter(!is.na(DOC_mgL)) %>% 
  pivot_longer(-c(1:4)) %>% 
  ggplot(aes(x=DateTime, y = value))+
  geom_point()+
  ylim(0,6)+
  scale_x_datetime(date_labels = "%b %y")+
  geom_vline(xintercept = ymd_hms("2021-08-19 00:00:00"))+   
  geom_vline(xintercept = ymd_hms("2021-09-23 00:00:00"))+   
  geom_vline(xintercept = ymd_hms("2022-11-17 00:00:00"))+   
  facet_grid(Site_filt~name, scales = "fixed")


stream_doc <-   chem %>% 
  filter(Reservoir == "CCR",
         Site > 51,
         DateTime >= ymd("2021-01-01")) %>% 
  mutate(Site_filt = ifelse(Site >= 100 & Site <200, 100, NA),
         Site_filt = ifelse(Site >= 200 & Site <300, 200, Site_filt),
         Site_filt = ifelse(Site >= 300 & Site <400, 300, Site_filt),
         Site_filt = ifelse(Site >= 400 & Site <500, 400, Site_filt),
         Site_filt = ifelse(Site >= 500, 500, Site_filt)
         ) %>% 
  filter(Site_filt != 200) %>%
  # select(Reservoir, Site_filt, DateTime, Depth_m, TN_ugL, TP_ugL, NO3NO2_ugL, NH4_ugL, SRP_ugL) %>% 
   select(Reservoir, Site_filt, DateTime, Depth_m, DOC_mgL) %>% 
    filter(!is.na(DOC_mgL)) %>% 
  ggplot(aes(x=DateTime, y = DOC_mgL, color = as.factor(Site_filt)))+ 
  geom_point(size=4)+
  geom_line(size=1)+
    ggtitle("A) Stream DOC")+
    ylim(0,6)+
    labs(color = "Stream Site",
       y = "DOC (mg/L)",
       x = element_blank())+
  # geom_vline(xintercept = ymd_hms("2021-08-19 00:00:00"))+   
  # geom_vline(xintercept = ymd_hms("2021-09-23 00:00:00"))+   
  # geom_vline(xintercept = ymd_hms("2022-11-17 00:00:00"))+
    scale_x_datetime(date_labels = "%b %y")+
  theme_bw()+
  theme(text = element_text(size = 21),
        legend.position = "top",
        legend.text = element_text(size = 18),
        axis.text = element_text(size = 21))+
  scale_color_manual(values = c("100" = "#0072B2", "300" = "#D55E00", "400" = "#CC79A7", "500" = "#999999"  ))


res_doc <- chem %>% 
  filter(Reservoir == "CCR",
         Site %in% c(50,51),
         DateTime >= ymd("2021-01-01"),
         Depth_m != 15) %>% 
  mutate(Depth_m = ifelse(Depth_m %in% c(20,21), 20, Depth_m)) %>%  
  # select(Reservoir, Site_filt, DateTime, Depth_m, TN_ugL, TP_ugL, NO3NO2_ugL, NH4_ugL, SRP_ugL) %>% 
  select(Reservoir, Site, DateTime, Depth_m, DOC_mgL) %>% 
      filter(!is.na(DOC_mgL)) %>% 
  ggplot(aes(x=DateTime, y = DOC_mgL, color = as.factor(Depth_m)))+ 
  geom_point(size=4)+
  geom_line(size=1)+
    ggtitle("B) Reservoir DOC")+
  labs(color = "Depth (m)",
       y = "DOC (mg/L)",
       x = element_blank())+
      ylim(0,6)+
  # geom_vline(xintercept = ymd_hms("2021-08-19 00:00:00"))+   
  # geom_vline(xintercept = ymd_hms("2021-09-23 00:00:00"))+   
  # geom_vline(xintercept = ymd_hms("2022-11-17 00:00:00"))+
    scale_x_datetime(date_labels = "%b %y")+
  theme_bw()+
  theme(text = element_text(size = 21),
        legend.position = "top",
        legend.text = element_text(size = 18),
        axis.text = element_text(size = 21))+
  scale_color_manual(values = c("0.1" = "#000000", "1.5" = "#E69F00", "6" = "#56B4E9", "9" = "#009E73", "20" = "#F0E442"))


# stream_doc | res_doc
# ggsave("./ESA_figures/doc_combo.png", width = 21, height = 7, units = "in")

## CV calcs
stream_doc_CV <- chem %>% 
  filter(Reservoir == "CCR",
         Site > 51,
         DateTime >= ymd("2021-01-01")) %>% 
  mutate(Site_filt = ifelse(Site >= 100 & Site <200, 100, NA),
         Site_filt = ifelse(Site >= 200 & Site <300, 200, Site_filt),
         Site_filt = ifelse(Site >= 300 & Site <400, 300, Site_filt),
         Site_filt = ifelse(Site >= 400 & Site <500, 400, Site_filt),
         Site_filt = ifelse(Site >= 500, 500, Site_filt)
         ) %>% 
  filter(Site_filt != 200) %>%
  # select(Reservoir, Site_filt, DateTime, Depth_m, TN_ugL, TP_ugL, NO3NO2_ugL, NH4_ugL, SRP_ugL) %>% 
   select(Reservoir, Site_filt, DateTime, Depth_m, DOC_mgL) %>% 
    filter(!is.na(DOC_mgL)) %>% 
  group_by(Site_filt) %>% 
  summarize(mean = mean(DOC_mgL, na.rm = T),
            sd = sd(DOC_mgL, na.rm = T)) %>% 
  mutate(CV = sd/mean)

stream_doc_CV <- stream_doc_CV %>% 
  rename(Depth_m = Site_filt) 

stream_doc_CV

res_doc_CV <- chem %>% 
  filter(Reservoir == "CCR",
         Site %in% c(50,51),
         DateTime >= ymd("2021-01-01"),
         Depth_m != 15) %>% 
  mutate(Depth_m = ifelse(Depth_m %in% c(20,21), 20, Depth_m)) %>%  
  # select(Reservoir, Site_filt, DateTime, Depth_m, TN_ugL, TP_ugL, NO3NO2_ugL, NH4_ugL, SRP_ugL) %>% 
  select(Reservoir, Site, DateTime, Depth_m, DOC_mgL) %>% 
      filter(!is.na(DOC_mgL)) %>% 
  group_by(Depth_m) %>% 
  summarize(mean = mean(DOC_mgL, na.rm = T),
            sd = sd(DOC_mgL, na.rm = T)) %>% 
  mutate(CV = sd/mean)

res_doc_CV <- res_doc_CV 
res_doc_CV

CV_plotting <- rbind(stream_doc_CV, res_doc_CV) %>% 
  mutate(Class = ifelse(Depth_m < 50, "Reservoir", "Stream")) %>% 
  select(Class,  Depth_m, mean, sd, CV)
  
level_order <- c("Stream", "Reservoir")

doc_cv_plot <- CV_plotting %>% 
  ggplot(aes(x = Class, y = CV))+
  geom_boxplot()+
  geom_point(aes(x = Class, y = CV, color = as.factor(Depth_m)), position = position_jitter(), size = 4)+
  labs(y = "DOC CV", x = element_blank())+
  ggtitle("C) DOC CV")+
  scale_x_discrete(limits = level_order) +
  theme_bw()+
  theme(text = element_text(size = 21),
        legend.position = "none",
        legend.text = element_text(size = 18),
        axis.text = element_text(size = 21))+
  scale_color_manual(values = c("0.1" = "#000000", "1.5" = "#E69F00", "6" = "#56B4E9", "9" = "#009E73", "20" = "#F0E442",
                                 "100" = "#0072B2", "300" = "#D55E00", "400" = "#CC79A7", "500" = "#999999"  ))


stream_doc | res_doc | doc_cv_plot

ggsave("./doc_combo.png", width = 23, height = 7.5, units = "in")



```


